/* The four calculators (Level 13, MR-067): How much home, House, Car and
   Retirement for two. One layout each: the one-sentence answer in large
   type, the compact input panel (prefilled, each field with its state),
   the charts, the detail table, and "Add this to my plan". Every number
   comes from engine/home.js, house.js, car.js and retire.js through
   engine/calculators.js; the views never do math. */
import { h, clear } from '../dom.js';
import * as F from '../../engine/format.js';
import * as Charts from '../charts.js';
import { runHome, runHouse, runCar, runRetire, retireInputOf, carOptionsOf } from '../../engine/calculators.js';
import { rentVsBuyRange, taxEffect, houseHack, houseFi, upfrontList } from '../../engine/house.js';
import { compareCars } from '../../engine/car.js';
import { retireFor } from '../../engine/retire.js';
import { answer, needsCard, inputPanel, detailTable, chartCard, addToPlan, planButton, months as monthsWord, fiWords } from '../calcbits.js';
import { homeAnswers as homeChart, downPaymentLadder as ladderChart, rentVsBuy as rvbChart, equityVsLoan as equityChart, carTco as tcoChart, carValueVsLoan as carValueChart, retireGrowth as retireChart } from '../../engine/chartdata-calc.js';
import { clientName } from '../app.js';

const money = c => F.dollarsWhole(c); const compact = c => F.dollarsCompact(c); const pct = (v, p) => F.percent(v, { places: p === undefined ? 0 : p });
const CALCS = { 'home-afford': drawHome, house: drawHouse, car: drawCar, retire: drawRetire };
const TITLES = { 'home-afford': ['How much home', 'How much home'], house: ['House', 'Owning a home'], car: ['Car', 'A car, or no car'], retire: ['Retirement for two', 'What your investing becomes'] };

export function mount(host, app) {
  const id = CALCS[app.route.params.id] ? app.route.params.id : 'home-afford'; const client = app.view === 'client';
  const name = (clientName(app.record) || 'Household').split(' ')[0];
  host.appendChild(h('header', null, h('h1', null, TITLES[id][client ? 1 : 0]), h('span', { class: 'sub' }, { 'home-afford': 'What a lender might approve, what is comfortable, and what keeps the FI date.', house: 'The full cost of owning, the loan, renting against buying, and a house hack.', car: 'New, used, lease or no car, side by side.', retire: 'What today’s investing becomes, and what more would add.' }[id]), h('div', { class: 'actions' }, h('a', { class: 'btn', href: '#/calculators' }, 'All calculators'))));
  const top = h('div', { class: 'calc-top' }); const body = h('div', { class: 'calc-body' }); host.appendChild(top); host.appendChild(body);
  const ctx = { app, client, name, top, body };
  function draw() { clear(top); clear(body); CALCS[id](ctx, draw); }
  ctx.redraw = draw;
  draw();
  return { update() { draw(); } };
}
const OPEN = {}; /* which input groups are open, per calculator, so a redraw keeps them */
const groupsPanel = (ctx, calcId, fields, groups, open) => { if (!OPEN[calcId]) OPEN[calcId] = new Set(window.innerWidth < 720 ? open.slice(0, 1) : open); return inputPanel(ctx.app, calcId, fields, groups, { clientName: ctx.name, openGroups: Array.from(OPEN[calcId]), onToggle: (gid, isOpen) => { if (isOpen) OPEN[calcId].add(gid); else OPEN[calcId].delete(gid); }, onChange: () => ctx.redraw() }); };
const needsOf = fields => fields.filter(f => f.state === 'missing').map(f => f.label);

/* ---- how much home ---- */
function drawHome(ctx, redraw) {
  const { app, client, name, top, body } = ctx; const H = runHome(app.record, app.result, app.data); const o = H.out; const inp = H.inp;
  const groups = [['hers', client ? 'Your numbers' : name + '’s numbers'], ['place', 'The place'], ['loan', 'The loan'], ['rules', 'The rules']];
  if (o.needs) { answer(top, 'Not yet', 'How much home needs ' + o.needs.join(' and ') + '.', { label: 'How much home' }); top.appendChild(needsCard(app, needsOf(H.fields).length ? needsOf(H.fields) : o.needs, { 'gross pay': '#/ledger/income', 'take-home pay': '#/ledger/income' })); body.appendChild(groupsPanel(ctx, 'home', H.fields, groups, ['hers'])); return; }
  const fi = o.fiSafe;
  answer(top, compact(o.comfortable.price), 'A lender might approve about ' + compact(o.lender.price) + '. Comfortable is about ' + compact(o.comfortable.price) + ', where the full cost of owning, ' + money(o.comfortable.cost.total) + ' a month, stays at ' + pct(o.comfortable.share) + ' of take-home.' + (fi && fi.price ? ' ' + (client ? 'Your FI date moves ' : 'The FI date moves ') + fi.allowed + ' months at most up to about ' + compact(fi.price) + '.' : ''), { label: 'Comfortable home price' });
  const cards = h('div', { class: 'grid grid-3 calc-answers' },
    answerTile('A lender might approve', compact(o.lender.price), money(o.lender.cost.lender) + ' a month to the lender; ' + (o.lender.binding === 'front' ? pct(o.lender.front) + ' of gross for housing binds' : pct(o.lender.back) + ' of gross for all debt binds')),
    answerTile('Comfortable', compact(o.comfortable.price), money(o.comfortable.cost.total) + ' a month all in, ' + pct(o.comfortable.share) + ' of take-home' + (inp.rentNow ? ', against ' + money(inp.rentNow) + ' rent today' : ''), true),
    fi ? answerTile(client ? 'Keeps your FI date' : 'Keeps the FI date', fi.price ? compact(fi.price) : 'none at this rate', fi.price && fi.effect ? money(fi.cost.total) + ' a month; ' + fiWords(fi.effect) : 'No price keeps the move under ' + fi.allowed + ' months; raise the allowance in the rules.') : answerTile(client ? 'Keeps your FI date' : 'Keeps the FI date', 'needs the FI date', 'Income, spending, balances and a birth date give the projection.'));
  top.appendChild(cards);
  body.appendChild(chartCard(client ? 'Three answers on how much home' : 'How much home: three answers', '', el => Charts.render('homeAnswers', el, homeChart(app.result), { client })));
  body.appendChild(groupsPanel(ctx, 'home', H.fields, groups, ['hers', 'loan']));
  body.appendChild(chartCard(client ? 'The down payment ladder' : 'Down payment ladder', 'Cash on hand ' + money(inp.cashAvailable || 0) + ', saving ' + money(inp.savingsPaceMonthly || 0) + ' a month', el => Charts.render('downPaymentLadder', el, ladderChart(app.result), { client })));
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'The ladder, step by step'), detailTable(['Down', 'Price', 'Cash to close', 'Mortgage insurance a month', 'Saved by'], o.ladder.map(l => ({ cells: [pct(l.downPct, l.downPct < 0.04 ? 1 : 0), compact(l.price), money(l.cashToClose), l.mi ? money(l.mi) : 'none', l.months === 0 ? 'now' : l.months === null ? 'no pace' : monthsWord(l.months)] }))), h('p', { class: 'small muted' }, 'Price is the lower of the lender and comfortable answers at each step. Under 20% down, conventional loans carry mortgage insurance until the loan is 80% of the value.')));
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'Cash to close at the comfortable price', h('span', { class: 'tag' }, compact(o.comfortable.price))), detailTable(['', 'Amount'], o.cashToClose.parts.map(p => ({ cells: [p[0], money(p[1])] })), { foot: ['Total', money(o.cashToClose.total)] }), h('p', { class: 'small muted' }, 'Closing costs at ' + pct(o.cashToClose.closingShare, 1) + ' of price for ' + inp.state + '; prepaids are taxes, the first year of insurance and interest to the first payment; the escrow cushion is two months; moving and a first-year repairs reserve of 1% are included because they always come.')));
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'The monthly cost at the comfortable price'), detailTable(['', 'A month'], o.comfortable.cost.parts.map(p => ({ cells: [p[0], money(p[1])] })), { foot: ['Total', money(o.comfortable.cost.total)] })));
  if (o.hack) body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'With a roommate or a rented unit'), h('p', null, 'Counting ' + pct(o.hack.counted) + ' of ' + money(inp.rentalIncomeMonthly) + ' a month (check with a lender), the lender answer moves from ' + compact(o.hack.lenderWithout) + ' to ' + compact(o.lender.price) + ' and comfortable from ' + compact(o.hack.comfortableWithout) + ' to ' + compact(o.comfortable.price) + '.')));
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'Buy now or wait'), detailTable(['', 'Cash on hand', 'Highest down payment reachable', 'Price at that step'], o.wait.map(w => ({ cells: [w.months === 0 ? 'Now' : 'In ' + monthsWord(w.months), money(w.cash), w.reachable ? pct(w.reachable.downPct, w.reachable.downPct < 0.04 ? 1 : 0) : 'not yet', w.reachable ? compact(w.reachable.price) : 'keep saving'] }))), h('p', { class: 'small muted' }, 'The lender and comfortable answers do not change with time at the same pay; what changes is the down payment the cash reaches.')));
  const plan = planButton(app, 'Add this to my plan', () => { const price = o.comfortable.price; addToPlan(app, { blockType: 'home', name: 'Buy a home (comfortable)', answers: { price, downPct: inp.downPct, rateNote: o.comfortable.cost.total - (inp.rentNow || 0), years: 30 }, yearsOut: Math.max(1, Math.round(((o.ladder.find(l => l.downPct === inp.downPct) || {}).months || 12) / 12)), goal: { name: 'Down payment fund', targetCents: o.cashToClose.total } }); });
  if (plan) body.appendChild(h('div', { class: 'row calc-plan' }, plan, h('span', { class: 'small muted' }, 'A Buy a home block at the comfortable price (its monthly cost less today’s rent) and a down payment goal of ' + money(o.cashToClose.total) + ' on the goal timeline.')));
}
const answerTile = (label, big, line, pick) => h('div', { class: 'calc-tile' + (pick ? ' chosen' : '') }, h('div', { class: 'tile-label' }, label), h('div', { class: 'tile-value' }, big), h('div', { class: 'small' }, line));

/* ---- the house ---- */
function drawHouse(ctx, redraw) {
  const { app, client, name, top, body } = ctx; const Hs = runHouse(app.record, app.result, app.data); const inp = Hs.inp; const lib = app.data.housingCosts;
  const groups = [['home', 'The home'], ['place', 'The place'], ['loan', 'The loan'], ['rent', 'Renting, for the comparison'], ['hack', 'House hack']];
  if (!Hs.own) { answer(top, 'Not yet', 'The house calculator needs a price.', { label: 'Owning a home' }); body.appendChild(groupsPanel(ctx, 'house', Hs.fields, groups, ['home'])); return; }
  const own = Hs.own; const first = own.first; const share = inp.takeHomeMonthly ? first.total / inp.takeHomeMonthly : null;
  const rvb = inp.rentNow > 0 ? rentVsBuyRange(lib, inp, { years: 30, rentMonthly: inp.rentNow, rentGrowth: inp.rentGrowth, rentersInsuranceMonthly: inp.rentersInsuranceMonthly, securityDepositMonths: inp.securityDepositMonths, stockReturn: inp.stockReturn, capitalGainsRate: inp.capitalGainsRate, appreciation: inp.appreciation }) : null;
  const up = upfrontList(lib, inp); const tax = taxEffect(lib, app.data.tax2026, own, { filingStatus: app.record.sun.f.filingStatus && app.record.sun.f.filingStatus.v || 'single', grossAnnual: (inp.grossMonthly || 0) * 12 });
  const hack = inp.units > 0 ? houseHack(lib, own, { units: inp.units, rentPerUnit: inp.rentPerUnit, vacancy: inp.vacancy, extraCosts: inp.extraCosts }) : null; const fi = houseFi(app.result, own, up.ctc, inp.rentNow || 0, 30);
  const at = rvb ? rvb.likely.at(inp.years) : null;
  answer(top, money(first.total), 'A ' + compact(inp.price) + ' home with ' + pct(inp.downPct, inp.downPct < 0.04 ? 1 : 0) + ' down costs about ' + money(first.total) + ' a month all in' + (share !== null ? ', ' + pct(share) + ' of take-home against the ' + pct(inp.comfortableShare) + ' line' : '') + '.' + (rvb ? (rvb.likely.breakEvenYear ? ' Buying pulls ahead of renting in year ' + rvb.likely.breakEvenYear + '.' : ' Renting stays ahead across thirty years at these assumptions.') : '') + ' ' + (fi.deltaMonths !== null ? 'Owning ' + fiWords(fi) + '.' : ''), { label: 'The full cost of owning, a month' });
  top.appendChild(h('div', { class: 'grid grid-3 calc-answers' }, answerTile('Up front', money(up.total), 'Down payment, costs, prepaids, moving and repairs'), answerTile('Mortgage insurance', first.mi ? money(first.mi) + ' a month' : 'none', own.miEndsMonth ? 'ends after ' + monthsWord(own.miEndsMonth) + ' at 20% equity' : inp.loanType === 'fha' ? (inp.downPct < 0.10 ? 'for the life of an FHA loan under 10% down' : 'for 11 years on an FHA loan') : 'not needed at this down payment'), answerTile(client ? 'Your FI date' : 'FI date', fi.deltaMonths === null || fi.deltaMonths === undefined ? 'needs the projection' : (fi.deltaMonths > 0 ? '+' : '') + F.months(Math.abs(fi.deltaMonths)).replace(/^/, fi.deltaMonths < 0 ? '-' : ''), 'with the house, against renting at ' + money(inp.rentNow || 0))));
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'What the payment is made of'), detailTable(['', 'A month, year one'], first.parts.map(p => ({ cells: [p[0], money(p[1])] })), { foot: ['Total', money(first.total)] }), h('p', { class: 'small muted' }, 'Loan ' + money(first.loan) + ' at ' + pct(inp.rate, 3) + ' over ' + inp.termYears + ' years; payment ' + money(own.payment) + ' with ' + money(own.totalInterest) + ' of interest over the loan' + (inp.extraPrincipal ? ', paid off in ' + monthsWord(own.loanMonths) + ' with the extra principal' : '') + '. Taxes and insurance grow with the home’s value and inflation.')));
  body.appendChild(groupsPanel(ctx, 'house', Hs.fields, groups, ['home', 'loan']));
  if (rvb) body.appendChild(chartCard(client ? 'Renting against buying, year by year' : 'Rent against buy', at ? 'At year ' + at.year + ': buying ' + compact(at.buyerNetWorth) + ', renting ' + compact(at.renterNetWorth) : '', el => Charts.render('rentVsBuy', el, rvbChart(app.result), { client })));
  body.appendChild(chartCard(client ? 'Home value against the loan' : 'Equity against the loan', 'Equity after ' + inp.years + ' years: ' + compact(own.years[Math.min(own.years.length, inp.years) - 1].equity), el => Charts.render('equityVsLoan', el, equityChart(app.result), { client })));
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'Up front', h('span', { class: 'tag' }, 'cash to close and the rest')), detailTable(['', 'Amount'], up.parts.map(p => ({ cells: [p[0], money(p[1])] })), { foot: ['Total', money(up.total)] })));
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'Taxes'), h('p', null, tax.itemizes ? 'Itemizing beats the standard deduction in year one: ' + money(tax.interest) + ' of mortgage interest and ' + money(tax.salt) + ' of state and local taxes against a ' + money(tax.standard) + ' standard deduction, saving about ' + money(tax.savingMonthly) + ' a month at the ' + pct(tax.marginal) + ' bracket.' : 'The standard deduction (' + money(tax.standard) + ') is larger than the mortgage interest and property tax together (' + money(tax.itemized) + '), so the tax break for owning is zero here. Most clients will not itemize.')));
  if (rvb) body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'Year by year', h('span', { class: 'tag' }, 'likely appreciation ' + pct(inp.appreciation, 1))), detailTable(['Year', 'Owning a month', 'Renting a month', 'Home value', 'Loan', 'Buying: worth', 'Renting: worth'], [1, 3, 5, 7, 10, 15, 20, 30].filter(y => y <= 30).map(y => { const r = rvb.likely.at(y); return { cls: y === inp.years ? 'is-pick' : '', cells: [String(y), money(r.buyerMonthly), money(r.renterMonthly), compact(r.homeValue), compact(r.loanBalance), compact(r.buyerNetWorth), compact(r.renterNetWorth)] }; })), h('p', { class: 'small muted' }, 'The renter invests the down payment and closing costs up front and the monthly difference whichever side is cheaper; the buyer invests the difference when owning costs less. Buying is worth the home after ' + pct(lib.comparison.sellingCostShare) + ' selling costs, minus the loan; renting is the portfolio after capital gains tax.')));
  if (hack) body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'House hack'), h('p', null, inp.units + (inp.units === 1 ? ' room or unit' : ' rooms or units') + ' at ' + money(inp.rentPerUnit) + ' brings in ' + money(hack.netRent) + ' a month after ' + pct(hack.vacancy) + ' vacancy and ' + money(hack.extraCosts) + ' of extra costs: housing costs ' + money(hack.housingCost) + ' a month instead of ' + money(hack.before) + '.')));
  const plan = planButton(app, 'Add this to my plan', () => addToPlan(app, { blockType: 'home', name: 'Buy a home (' + compact(inp.price) + ')', answers: { price: inp.price, downPct: inp.downPct, rateNote: first.total - (inp.rentNow || 0), years: 30 }, yearsOut: 1, goal: { name: 'Down payment and closing fund', targetCents: up.ctc.total } }));
  if (plan) body.appendChild(h('div', { class: 'row calc-plan' }, plan, h('span', { class: 'small muted' }, 'A Buy a home block at this price and a goal for the cash to close.')));
}

/* ---- the car ---- */
function drawCar(ctx, redraw) {
  const { app, client, name, top, body } = ctx; const Cc = runCar(app.record, app.result, app.data); const inp = Cc.inp; const out = Cc.out; const opts = out.options;
  const groups = [['hers', client ? 'Your numbers' : name + '’s numbers'], ['place', 'The place'], ['use', 'How you would use it'], ['options', 'Which options to compare'], ['new', 'Buying new'], ['used', 'Buying used'], ['lease', 'Leasing'], ['none', 'No car']];
  if (!opts.length) { answer(top, 'Pick an option', 'Turn on at least one of new, used, lease or no car.', { label: 'A car, or no car' }); body.appendChild(groupsPanel(ctx, 'car', Cc.fields, groups, ['options'])); return; }
  const best = opts.find(o => o.kind === out.cheapest); const sorted = opts.slice().sort((a, b) => a.costPerMonth - b.costPerMonth);
  answer(top, money(best.costPerMonth) + ' a month', best.label + ' costs least: ' + money(best.costPerMonth) + ' a month over ' + inp.keepYears + ' years' + (inp.transportNowMonthly ? ', against ' + money(inp.transportNowMonthly) + ' spent on getting around today' : '') + '.' + (sorted[1] ? ' ' + sorted[1].label + ' is next at ' + money(sorted[1].costPerMonth) + '.' : '') + (best.fi && best.fi.deltaMonths !== null ? ' It ' + fiWords(best.fi) + '.' : ''), { label: 'True cost a month, the cheapest option' });
  top.appendChild(h('div', { class: 'grid calc-answers', style: { gridTemplateColumns: 'repeat(' + Math.min(4, opts.length) + ', minmax(0, 1fr))' } }, opts.map(o => answerTile(o.label, money(o.costPerMonth) + '/mo', (o.costPerMile !== null ? F.dollars(o.costPerMile) + ' a mile; ' : '') + (o.fi && o.fi.deltaMonths !== null ? fiWords(o.fi) : 'no FI date yet'), o.kind === out.cheapest))));
  body.appendChild(chartCard(client ? 'What each car choice costs' : 'Total cost by option', inp.keepYears + ' years, by what the money goes to', el => Charts.render('carTco', el, tcoChart(app.result), { client })));
  body.appendChild(groupsPanel(ctx, 'car', Cc.fields, groups, ['options', 'use']));
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'Side by side'), detailTable([''].concat(opts.map(o => o.label)), [
    { cells: ['Up front'].concat(opts.map(o => money(o.upfront.total))) },
    { cells: ['Payment a month'].concat(opts.map(o => o.monthlyPayment ? money(o.monthlyPayment) + (o.lease ? ' (lease)' : '') : 'none')) },
    { cells: ['Rate'].concat(opts.map(o => o.apr !== undefined && o.kind !== 'none' ? pct(o.apr, 1) + (o.lease ? ' (money factor ' + o.lease.moneyFactor.toFixed(5) + ' x 2,400)' : '') : '')) },
    { cells: ['Running costs a month'].concat(opts.map(o => money(o.running.total))) },
    { cells: ['Interest and lease charges'].concat(opts.map(o => money(o.interest))) },
    { cells: ['Worth at the end'].concat(opts.map(o => o.kind === 'none' || o.kind === 'lease' ? 'nothing to sell' : money(o.endValue))) },
    { cells: ['Months underwater'].concat(opts.map(o => o.underwaterMonths ? o.underwaterMonths + ' (up to ' + money(o.worstGap) + ')' : 'none')) },
    { cells: ['Total over ' + inp.keepYears + ' years'].concat(opts.map(o => money(o.totalCost))) },
    { cls: 'is-pick', cells: ['True cost a month'].concat(opts.map(o => money(o.costPerMonth))) },
    { cells: ['Cost a mile'].concat(opts.map(o => o.costPerMile !== null ? F.dollars(o.costPerMile) : '')) },
  ])));
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'The rules', h('span', { class: 'tag' }, '20/3/8 and 20/4/10')), detailTable(['Rule', 'Option', '20% down', 'Loan length', 'Under the share of gross', 'Passes'], opts.filter(o => o.rules).flatMap(o => o.rules.map(r => ({ cls: r.pass ? 'is-pick' : '', cells: [r.label, o.label, r.down.ok ? 'yes (' + money(r.down.have) + ')' : 'no (' + money(r.down.have) + ' of ' + money(r.down.need) + ')', r.term.ok ? 'yes (' + r.term.have + ' months)' : 'no (' + r.term.have + ' of ' + r.term.max + ')', r.share.ok === null ? 'needs gross pay' : r.share.ok ? 'yes (' + pct(r.share.have, 1) + ')' : 'no (' + pct(r.share.have, 1) + ' of ' + pct(r.share.max) + ')', r.pass ? 'yes' : 'no'] })))), h('p', { class: 'small muted' }, 'Money Guy 20/3/8: twenty percent down, a loan no longer than three years, and all car costs under eight percent of gross. The common 20/4/10 allows four years and ten percent.')));
  const withLoan = opts.filter(o => o.schedule);
  if (withLoan.length) body.appendChild(chartCard(client ? 'The car’s value against its loan' : 'Value against loan balance', withLoan.some(o => o.underwaterMonths) ? 'Underwater months: ' + withLoan.map(o => o.label + ' ' + o.underwaterMonths).join(', ') : 'Never underwater', el => Charts.render('carValueVsLoan', el, carValueChart(app.result), { client })));
  opts.forEach(o => body.appendChild(h('section', { class: 'panel' }, h('h2', null, o.label, h('span', { class: 'tag' }, money(o.costPerMonth) + ' a month')), h('div', { class: 'grid grid-2' }, h('div', null, h('h3', null, 'Up front'), detailTable(['', 'Amount'], o.upfront.parts.map(p => ({ cells: [p[0], money(p[1])] })), { foot: ['Total', money(o.upfront.total)] })), h('div', null, h('h3', null, 'Running costs'), detailTable(['', 'A month'], o.running.parts.map(p => ({ cells: [p[0], money(p[1])] })), { foot: ['Total', money(o.running.total)] }))), o.lease ? h('p', { class: 'small muted' }, 'Lease: capitalized cost ' + money(o.lease.cap) + ', residual ' + money(o.lease.residual) + ', depreciation ' + money(o.lease.depreciationFee) + ' plus finance charge ' + money(o.lease.financeFee) + ' plus tax ' + money(o.lease.taxOnPayment) + ' a month; acquisition and disposition fees and ' + money(o.lease.overage) + ' of mileage overage counted.') : null)));
  const plan = planButton(app, 'Add the cheapest car option to my plan', () => { const o = best.kind === 'none' ? sorted.find(x => x.kind !== 'none') || best : best; if (o.kind === 'none') { app.toast('No car is already the plan: nothing to add.'); return; } addToPlan(app, { blockType: 'car', name: o.label + ' (' + compact(o.price) + ')', answers: { price: o.price, tradeIn: 0, financed: o.price ? Math.round(Math.max(0, o.financed) / o.price * 100) / 100 : 0, years: Math.max(1, Math.round((o.lease ? o.lease.months : (inp.newTerm || 60)) / 12)) }, yearsOut: 1, goal: { name: 'Car fund', targetCents: o.upfront.total } }); });
  if (plan) body.appendChild(h('div', { class: 'row calc-plan' }, plan, h('span', { class: 'small muted' }, 'A Replace the car block with the price and the financed share, and a car fund goal for the cash up front.')));
}

/* ---- retirement for two ---- */
function drawRetire(ctx, redraw) {
  const { app, client, name, top, body } = ctx; const R = runRetire(app.record, app.result, app.data); const o = R.out; const inp = R.inp;
  const groups = [['you', client ? 'You' : name], ['partner', 'Your partner'], ['assume', 'Assumptions'], ['potential', 'The potential']];
  if (o.needs) { answer(top, 'Not yet', 'This needs ' + o.needs.join(', ') + '.', { label: 'What your investing becomes' }); top.appendChild(needsCard(app, needsOf(R.fields), { 'Your age': '#/home', 'Invested today': '#/ledger/invest', 'Investing a month': '#/ledger/invest' })); body.appendChild(groupsPanel(ctx, 'retire', R.fields, groups, ['you'])); return; }
  const two = o.people.length > 1;
  answer(top, compact(o.atRetirement.balance), (client ? 'Keep investing as you do and by age ' : 'At today’s pace, by age ') + o.horizonAge + (two ? ' (when ' + o.people[1].name + ' retires)' : '') + ' the two of you' .replace(' the two of you', two ? ' the two of you' : ' you') + ' would have about ' + compact(o.atRetirement.balance) + ': ' + compact(o.totalContributed) + ' put in and ' + compact(o.totalGrowth) + ' of growth, or about ' + money(o.incomeMonthly) + ' a month at a ' + pct(o.withdrawalRate, 1) + ' withdrawal.' + (o.extraMonthly ? ' Investing ' + money(o.extraMonthly) + ' more a month' + (o.extraFromYear ? ' starting in ' + o.extraFromYear + ' years' : '') + ' would make it about ' + compact(o.potentialAtRetirement.balance) + ', ' + compact(o.gain) + ' more.' : ''), { label: 'What today’s investing becomes' });
  top.appendChild(h('div', { class: 'grid grid-2 calc-answers' }, answerTile('What will be', compact(o.atRetirement.balance), 'at today’s pace by ' + o.horizonAge + (o.enoughAge ? '; enough for today’s spending at ' + o.enoughAge : o.fiNumber ? '; enough would be ' + compact(o.fiNumber) : '')), answerTile('What could be', compact(o.potentialAtRetirement.balance), (o.extraMonthly ? 'with ' + money(o.extraMonthly) + ' more a month' + (o.maxOut ? ' (maxing the ' + o.maxOut.label + ')' : '') + (o.extraFromYear ? ', from year ' + o.extraFromYear : '') : 'set an amount in the potential group') + (o.enoughAgePot && o.enoughAgePot !== o.enoughAge ? '; enough at ' + o.enoughAgePot : ''), true)));
  body.appendChild(chartCard(client ? 'What your investing becomes' : 'Investment growth', compact(o.totalContributed) + ' put in, ' + compact(o.totalGrowth) + ' from growth', el => Charts.render('retireGrowth', el, retireChart(app.result), { client })));
  body.appendChild(groupsPanel(ctx, 'retire', R.fields, groups, ['you', 'potential']));
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'Each person'), detailTable(['', 'Retires at', 'Investing a month', 'At retirement', 'Put in', 'Growth'], o.people.map(p => ({ cells: [p.name, String(p.retireAge), money(p.monthly), compact(p.atRetirement), compact(p.contributed), compact(p.growth)] }))), h('p', { class: 'small muted' }, 'Returns are after inflation, so the totals read in today’s dollars. Contributions stop at each person’s retirement age; the balance keeps growing until the later one.')));
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'Year by year'), detailTable(['Age', 'Put in', 'Growth', 'Balance', 'With more'], o.years.filter((y, i) => i % 5 === 0 || i === o.years.length - 1).map((y, i) => ({ cells: [String(y.age), compact(y.contributed), compact(y.growth), compact(y.balance), compact(o.potentialYears[o.years.indexOf(y)].balance)] })))));
  const plan = planButton(app, 'Make the potential the plan', () => { app.change(rec => { const Ccal = rec.calculators || {}; const r = Object.assign({}, Ccal.retire || {}, { committed: { extraMonthly: o.extraMonthly, at: new Date().toISOString().slice(0, 10) } }); rec.calculators = Object.assign({}, Ccal, { retire: r }); return true; }, { reason: 'calc' }); app.toast('Noted: ' + money(o.extraMonthly) + ' more a month is the plan. The money comes from the surplus, which the projection already counts.'); });
  if (plan) body.appendChild(h('div', { class: 'row calc-plan' }, plan, h('span', { class: 'small muted' }, 'Investing more moves money from cash to accounts; the FI projection already counts the surplus as saved, so this is a commitment, not a new block.')));
}
