/* The cash flow calendar (Level 13, MR-067). Every tab is a reading of the
   one day-by-day run in engine/cashcal.js: the month grid, the weeks, the
   balance line with the floor and the outlook band, the paycheck map, the
   year strip, the agenda, and the cards. The tools (can I spend this, the
   bill timing fixer, the outlook, an income shock, life events, the spend
   logger, the weekly check-in, dates and the floor) are drawers. The
   Ledger owns the amounts; this screen owns only the timing, written to
   record.calendar through the record API. Views never do math. */
import { h, clear } from '../dom.js';
import * as F from '../../engine/format.js';
import * as Charts from '../charts.js';
import * as C from '../../engine/cashcal.js';
import { calendarBalance as balanceData, paycheckMap as paycheckData, yearStrip as yearData } from '../../engine/chartdata-calc.js';
import { answer, chartCard, detailTable } from '../calcbits.js';
import { parseSaid } from '../../engine/parse.js';
import { closeOverlay, clientName } from '../app.js';
import { setDateValue } from '../datepicker.js';

const TABS = [['grid', 'Month'], ['weeks', 'Weeks'], ['line', 'Balance'], ['paychecks', 'Paychecks'], ['year', 'Year'], ['agenda', 'Next 14 days'], ['cards', 'Cards']];
const state = { tab: null, days: null, outlook: false, maybe: 'likely', outlookCache: null };
const money = c => F.dollarsWhole(c); const short = iso => new Date(iso + 'T00:00:00Z').toLocaleDateString('en-US', { month: 'short', day: 'numeric', timeZone: 'UTC' });
const ordinal = n => { const s = ['th', 'st', 'nd', 'rd']; const v = n % 100; return n + (s[(v - 20) % 10] || s[v] || s[0]); };
const dayWord = iso => { const n = parseInt(iso.slice(8, 10), 10); const s = ['th', 'st', 'nd', 'rd']; const v = n % 100; return 'the ' + n + (s[(v - 20) % 10] || s[v] || s[0]); };
const KIND_WORD = { income: 'Pay', 'maybe-in': 'Maybe in', bill: 'Bill', paylater: 'Pay later', transfer: 'Transfer', 'transfer-in': 'Transfer in', 'to-goals': 'To goals', 'card-payment': 'Card payment', 'loan-payment': 'Loan payment', interest: 'Interest', 'late-fee': 'Late fee', statement: 'Statement', shortfall: 'Could not pay', everyday: 'Everyday', log: 'Logged', 'auto-cover': 'Topped up', sweep: 'Sweep' };

export function mount(host, app) {
  const client = app.view === 'client'; const conv = app.data.calendar; const name = (clientName(app.record) || 'Household').split(' ')[0];
  if (!state.tab) state.tab = window.innerWidth < 720 ? 'weeks' : 'grid';
  if (app.route.params.id && TABS.some(t => t[0] === app.route.params.id)) state.tab = app.route.params.id;
  const header = h('header', null, h('h1', null, client ? 'Your month, day by day' : 'Cash flow calendar'), h('span', { class: 'sub' }, client ? 'Paydays against bills, and what is safe to spend.' : 'Paydays against bills, day by day.'));
  const actions = h('div', { class: 'actions' }); header.appendChild(actions); host.appendChild(header);
  const top = h('div', { class: 'calc-top' }); const tabs = h('nav', { class: 'calc-tabs', 'aria-label': 'Views' }); const body = h('div', { class: 'stack cal-body' });
  host.appendChild(top); host.appendChild(tabs); host.appendChild(body);
  const ctx = { app, client, conv, name }; ctx.redraw = () => draw();
  function model() { return C.buildModel(app.record, app.result, app.data, { days: state.days || C.calendarOf(app.record).window || conv.defaultWindowDays }); }
  function draw() {
    clear(actions); clear(top); clear(tabs); clear(body);
    const m = model(); ctx.m = m;
    actions.appendChild(h('select', { class: 'select', 'aria-label': 'Window', onChange: e => { state.days = +e.target.value; draw(); } }, conv.windows.map(d => h('option', { value: String(d), selected: d === m.days }, d === 365 ? '12 months' : d + ' days'))));
    if (!client) actions.appendChild(h('select', { class: 'select', 'aria-label': 'Tools', onChange: e => { const v = e.target.value; e.target.value = ''; if (v) TOOLS[v](ctx, draw); } }, h('option', { value: '' }, 'Tools'), Object.keys(TOOLS).map(k => h('option', { value: k }, TOOL_LABELS[k]))));
    else actions.appendChild(h('button', { class: 'btn', onClick: () => TOOLS.spend(ctx, draw) }, 'Can I spend this?'));
    if (!m.accounts.length || !m.incomes.length) {
      top.appendChild(h('section', { class: 'panel calc-needs' }, h('h2', null, client ? 'A few facts first' : 'Needs'), h('p', null, 'The calendar needs a checking or savings balance and an income with its pay frequency.'), h('ul', null, [!m.accounts.length ? h('li', null, h('a', { href: '#/ledger/invest/bank' }, 'A checking account balance')) : null, !m.incomes.length ? h('li', null, h('a', { href: '#/ledger/income' }, 'An income with how often it is paid')) : null].concat(m.needs.map(n => h('li', null, h('a', { href: '#/ledger/' + (n.rowId ? 'spending' : 'invest') }, n.what)))).filter(Boolean))));
      return;
    }
    const run = C.simulate(m, { maybeMode: state.maybe }); ctx.run = run;
    const safe = run.safeToSpend.today; const low = run.low;
    answer(top, money(safe), (client ? 'Your tightest day is ' : name + '’s tightest day is ') + dayWord(low.date) + ', at ' + money(low.cents) + (low.cents < m.floor ? (m.floor ? ', under the floor of ' + money(m.floor) : ', under zero') : '') + '.' + (run.shortfalls.length ? ' ' + run.shortfalls.length + (run.shortfalls.length === 1 ? ' bill could not be paid without breaking the floor.' : ' bills could not be paid without breaking the floor.') : ''), { label: 'Safe to spend today' + (run.safeToSpend.nextIncome ? ', until pay on ' + short(run.safeToSpend.nextIncome) : '') });
    const notes = []; if (m.floorSource === 'cushion-account') notes.push('The cushion sits in savings, so the floor on checking is zero.'); else if (m.floorSource === 'lean') notes.push('Floor: the lean month, ' + money(m.floor) + '.'); else if (m.floorSource === 'fixed') notes.push('Floor: ' + money(m.floor) + ', set by the coach.'); else if (m.floorSource === 'lean-unfunded') notes.push('No floor yet: the lean month step is not funded.');
    if (m.incomes.some(i => i.estimated) || m.bills.some(b => b.estimated) || m.cards.some(c => c.estimated)) notes.push(client ? 'Some dates are estimates until your coach sets them.' : 'Some dates are estimates: Tools, then Dates and the floor.');
    if (m.maybe.length) notes.push('Maybe money counted: ' + ({ ignore: 'none of it', likely: 'the likely items (60% and up)', weighted: 'weighted by likelihood' }[state.maybe]) + '.');
    if (notes.length && !client) top.appendChild(h('p', { class: 'small muted calc-notes' }, notes.join(' ')));
    else if (client && m.incomes.some(i => i.estimated) || (client && m.bills.some(b => b.estimated))) top.appendChild(h('p', { class: 'small muted calc-notes' }, 'Some dates are estimates until your coach sets them.'));
    TABS.forEach(([id, label]) => { if (id === 'cards' && !m.cards.length) return; tabs.appendChild(h('button', { class: 'tab' + (state.tab === id ? ' active' : ''), 'aria-pressed': String(state.tab === id), onClick: () => { state.tab = id; history.replaceState(null, '', '#/calendar/' + id); draw(); } }, label)); });
    ({ grid: drawGrid, weeks: drawWeeks, line: drawLine, paychecks: drawPaychecks, year: drawYear, agenda: drawAgenda, cards: drawCards }[state.tab] || drawGrid)(body, ctx, draw);
  }
  draw();
  return { update() { state.outlookCache = null; draw(); } };
}

/* ---- tabs ---- */
function balanceClass(cents, m) { const week = Math.round(m.everydayMonthly * 7 / 30.44); return cents < m.floor ? 'under' : cents < m.floor + week ? 'near' : 'ok'; }
function drawGrid(body, ctx, redraw) {
  const { run, m, app } = ctx; const byDate = {}; run.days.forEach(d => { byDate[d.date] = d; });
  const first = run.days[0].date, last = run.days[run.days.length - 1].date; const months = [];
  let y = +first.slice(0, 4), mo = +first.slice(5, 7); while (y < +last.slice(0, 4) || (y === +last.slice(0, 4) && mo <= +last.slice(5, 7))) { months.push([y, mo]); mo++; if (mo > 12) { mo = 1; y++; } }
  months.forEach(([yy, mm]) => {
    const n = C.dim(yy, mm); const lead = new Date(Date.UTC(yy, mm - 1, 1)).getUTCDay(); const cells = [];
    for (let i = 0; i < lead; i++) cells.push(h('span', { class: 'cal-cell blank', 'aria-hidden': 'true' }));
    for (let d = 1; d <= n; d++) {
      const iso = yy + '-' + String(mm).padStart(2, '0') + '-' + String(d).padStart(2, '0'); const day = byDate[iso];
      if (!day) { cells.push(iso > last ? h('span', { class: 'cal-cell blank', 'aria-hidden': 'true' }) : h('span', { class: 'cal-cell past' }, h('b', null, String(d)))); continue; }
      const marks = day.events.filter(e => e.kind !== 'everyday' && e.kind !== 'statement');
      const icons = []; if (marks.some(e => e.kind === 'income')) icons.push(h('i', { class: 'ci ci-pay', title: 'Payday' }, 'Pay')); if (marks.some(e => e.kind === 'bill' || e.kind === 'loan-payment')) icons.push(h('i', { class: 'ci ci-bill', title: 'Bill' }, 'Bill')); if (marks.some(e => e.kind === 'card-payment')) icons.push(h('i', { class: 'ci ci-card', title: 'Card due' }, 'Card')); if (marks.some(e => e.kind === 'paylater')) icons.push(h('i', { class: 'ci ci-later', title: 'Pay later' }, 'Later')); if (marks.some(e => e.kind === 'maybe-in' || e.maybe)) icons.push(h('i', { class: 'ci ci-maybe', title: 'Maybe money' }, '?')); if (marks.some(e => e.kind === 'shortfall')) icons.push(h('i', { class: 'ci ci-short', title: 'Could not pay' }, 'Short'));
      cells.push(h('button', { class: 'cal-cell ' + balanceClass(day.primary, m) + (iso === run.low.date ? ' is-low' : '') + (iso === run.start ? ' is-today' : ''), 'aria-label': short(iso) + ', balance ' + money(day.primary) + (marks.length ? ', ' + marks.length + ' items' : ''), onClick: () => dayDrawer(ctx, day, redraw) }, h('b', null, String(d)), h('span', { class: 'cal-icons' }, icons.slice(0, 3)), h('small', null, F.dollarsCompact(day.primary))));
    }
    while (cells.length % 7) cells.push(h('span', { class: 'cal-cell blank', 'aria-hidden': 'true' }));
    body.appendChild(h('section', { class: 'panel cal-month' }, h('h2', null, new Date(Date.UTC(yy, mm - 1, 1)).toLocaleDateString('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' })), h('div', { class: 'cal-grid', role: 'grid' }, h('div', { class: 'cal-head' }, ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'].map(w => h('span', null, w))), cells)));
  });
  body.appendChild(h('p', { class: 'small muted' }, 'Each day shows its end-of-day checking balance; shaded when it dips within a week of everyday spending of the floor, darker under it. Tap a day for what lands.'));
}
function dayDrawer(ctx, day, redraw) {
  const { app, client, m } = ctx; const ev = day.events.filter(e => e.kind !== 'everyday' || true);
  const everyday = day.events.filter(e => e.kind === 'everyday').reduce((s, e) => s + e.cents, 0);
  const list = day.events.filter(e => e.kind !== 'everyday').map(e => h('li', { class: 'cal-ev kind-' + e.kind }, h('span', { class: 'ev-kind' }, KIND_WORD[e.kind] || e.kind), h('span', { class: 'ev-label' }, e.label), h('span', { class: 'ev-amt num' }, e.cents ? (e.cents > 0 ? '+' : '') + money(e.cents) : (e.stmt !== undefined ? money(e.stmt) + ' due ' + short(e.due) : ''))));
  if (everyday) list.push(h('li', { class: 'cal-ev kind-everyday' }, h('span', { class: 'ev-kind' }, 'Everyday'), h('span', { class: 'ev-label' }, 'Groceries, getting around, the rest, spread by day'), h('span', { class: 'ev-amt num' }, money(everyday))));
  const bodyEl = h('div', { class: 'cal-day' }, h('h2', null, new Date(day.date + 'T00:00:00Z').toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', timeZone: 'UTC' }), day.date === ctx.run.low.date ? h('span', { class: 'tag' }, 'the tightest day') : null), list.length ? h('ul', { class: 'cal-evs' }, list) : h('p', { class: 'muted' }, 'Nothing lands on this day.'), h('p', { class: 'cal-bal' }, 'Balance after this day: ', h('strong', null, money(day.primary)), m.floor ? h('span', { class: 'small muted' }, ' (floor ' + money(m.floor) + ')') : null));
  if (!client) {
    const movable = ctx.run.items.filter(it => it.date === day.date && ['bill', 'paylater', 'transfer', 'income'].includes(it.kind) && !it.extra);
    if (movable.length) { bodyEl.appendChild(h('h3', null, 'Move or skip one occurrence')); movable.forEach(it => { const inp = h('input', { type: 'date', class: 'input', 'aria-label': 'New date for ' + it.label, value: it.date }); bodyEl.appendChild(h('div', { class: 'row cal-move' }, h('span', { class: 'ev-label' }, it.label + ' ' + money(it.cents)), inp, h('button', { class: 'btn small', onClick: () => { const v = inp.value; if (!v) return; app.change(rec => C.setCalendar(rec, cal => { cal.overrides[it.sourceId + '|' + it.origDate] = { date: v }; }, { session: app.session }), { reason: 'calendar' }); closeOverlay(); redraw(); } }, 'Move'), h('button', { class: 'btn small quiet', onClick: () => { app.change(rec => C.setCalendar(rec, cal => { cal.overrides[it.sourceId + '|' + it.origDate] = { skip: true }; }, { session: app.session }), { reason: 'calendar' }); closeOverlay(); redraw(); } }, 'Skip once'))); }); bodyEl.appendChild(h('p', { class: 'small muted' }, 'The rule is untouched; only this one occurrence moves.')); }
  }
  app.openDrawer(bodyEl, { label: 'Day', title: short(day.date) });
}
function drawWeeks(body, ctx) {
  const { run, m, client } = ctx; const rows = []; const days = run.days; let i = 0;
  const firstDow = new Date(days[0].date + 'T00:00:00Z').getUTCDay(); let span = 7 - firstDow;
  while (i < days.length) { const slice = days.slice(i, i + span); const inC = slice.reduce((s, d) => s + d.in, 0); const outC = slice.reduce((s, d) => s + d.out, 0); const end = slice[slice.length - 1]; const lowIn = slice.some(d => d.date === run.low.date); rows.push({ cls: balanceClass(end.primary, m) === 'under' ? 'is-under' : lowIn ? 'is-low' : '', cells: [short(slice[0].date) + ' to ' + short(end.date) + (lowIn ? ' (tightest day ' + dayWord(run.low.date) + ')' : ''), money(inC), money(outC), money(end.primary)] }); i += span; span = 7; }
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'Week by week'), detailTable(['Week', 'In', 'Out', 'Ending balance'], rows), h('p', { class: 'small muted' }, (client ? 'What comes in, what goes out, and where the week ends. ' : 'In, out and the end-of-week checking balance. ') + 'Everyday spending is spread across the days.')));
}
function drawLine(body, ctx) {
  const { app, run, m, client } = ctx; const d = balanceData(app.result);
  if (state.outlook) { if (!state.outlookCache) state.outlookCache = C.outlook(m, { runs: 60, band: true, maybeMode: state.maybe }); d.band = state.outlookCache.band; }
  body.appendChild(chartCard(client ? 'Your cash, day by day' : 'Checking balance, day by day', 'Lowest ' + money(run.low.cents) + ' on ' + short(run.low.date) + ' · Safe to spend today ' + money(run.safeToSpend.today), el => Charts.render('calendarBalance', el, d, { client })));
  const o = state.outlookCache;
  body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'Outlook', h('span', { class: 'tag' }, 'amounts wobble ' + Math.round((app.data.calendar.outlook.amountWobble) * 100) + '%, estimated dates shift a few days')), h('label', { class: 'calc-switch' }, h('input', { type: 'checkbox', checked: state.outlook, onChange: e => { state.outlook = e.target.checked; if (state.outlook && !state.outlookCache) state.outlookCache = C.outlook(m, { runs: app.data.calendar.outlook.runs, band: true, maybeMode: state.maybe }); ctx.redraw ? ctx.redraw() : app.rerender(); } }), h('span', null, state.outlook ? 'On: the band behind the line is where the balance landed in most runs' : 'Off')),
    o ? detailTable(['', 'Worst tenth', 'Typical', 'Best tenth'], [{ cells: ['Lowest point', money(o.low.worst), money(o.low.typical), money(o.low.best)] }, { cells: ['Cash at the end', money(o.end.worst), money(o.end.typical), money(o.end.best)] }, { cells: ['Card interest', money(o.interest.high), money(o.interest.typical), money(o.interest.low)] }]) : null,
    o ? h('p', { class: 'small' }, 'In ' + Math.round(o.shareBelowFloor * 100) + '% of ' + o.runs + ' runs a day dipped under the floor or a bill could not be paid.') : null));
}
function drawPaychecks(body, ctx) {
  const { app, run, client } = ctx; const d = paycheckData(app.result);
  body.appendChild(chartCard(client ? 'What each paycheck pays for' : 'Paycheck map', run.paychecks.length ? run.paychecks.length + ' paychecks in the window' : '', el => Charts.render('paycheckMap', el, d, { client })));
  run.paychecks.slice(0, 6).forEach(p => body.appendChild(h('section', { class: 'panel' }, h('h2', null, short(p.date) + ': ' + p.label + ' ' + money(p.cents), h('span', { class: 'tag' }, p.until ? 'until ' + short(p.until) : 'to the end of the window')), detailTable(['What it covers', 'Date', 'Amount'], p.bills.map(b => ({ cells: [b.label, short(b.date), money(b.cents)] })), { foot: ['Left after these', '', money(p.left)] }))));
}
function drawYear(body, ctx) { const { app, client } = ctx; const d = yearData(app.result); body.appendChild(chartCard(client ? 'Your year, month by month' : 'The year, month by month', d.months ? d.months.filter(mm => mm.tight).length + ' tight months of 12' : '', el => Charts.render('yearStrip', el, d, { client }))); if (d.months) body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'Each month'), detailTable(['Month', 'In', 'Out', 'Net', 'Lowest point'], d.months.map(mm => ({ cls: mm.tight ? 'is-low' : '', cells: [new Date(mm.ym + '-15T00:00:00Z').toLocaleDateString('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' }), money(mm.in), money(mm.out), money(mm.net), money(mm.low) + (mm.tight ? ' (tight)' : '')] }))))); }
function drawAgenda(body, ctx) { const { run } = ctx; const days = C.agenda(run, 14); body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'The next 14 days'), days.length ? h('div', { class: 'agenda' }, days.map(d => h('div', { class: 'agenda-day' }, h('h3', null, new Date(d.date + 'T00:00:00Z').toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', timeZone: 'UTC' }), h('span', { class: 'small muted' }, ' ends at ' + money(d.primary))), h('ul', { class: 'cal-evs' }, d.events.filter(e => e.kind !== 'everyday').map(e => h('li', { class: 'cal-ev kind-' + e.kind }, h('span', { class: 'ev-kind' }, KIND_WORD[e.kind] || e.kind), h('span', { class: 'ev-label' }, e.label), h('span', { class: 'ev-amt num' }, e.cents ? (e.cents > 0 ? '+' : '') + money(e.cents) : (e.stmt !== undefined ? money(e.stmt) + ' due ' + short(e.due) : '')))))))) : h('p', { class: 'muted' }, 'Nothing but everyday spending in the next two weeks.'))); }
function drawCards(body, ctx) {
  const { app, run, m, client } = ctx; const S = app.result.sun && app.result.sun.outputs; const wallet = S && S.debt && S.debt.wallet ? S.debt.wallet.cards : [];
  m.cards.forEach(c => {
    const st = run.cards[c.id]; const w = wallet.find(x => x.rowId === c.id); const util = C.utilizationCheck(c, run, app.data.calendar.cards.utilizationWarn);
    const months = Object.keys(st.interestByMonth).sort();
    body.appendChild(h('section', { class: 'panel card-panel' }, h('h2', null, c.name, h('span', { class: 'tag' }, c.payInFull ? 'paid in full every month' : st.revolving ? 'carrying a balance' : 'not revolving')),
      h('div', { class: 'kpis' }, kpi('Balance now', money(c.balance)), kpi('At the end of the window', money(st.balance)), kpi(client ? 'Interest in the window' : 'Interest charged', money(st.interest)), kpi('Statement closes', 'the ' + ordinal(c.stmtDay) + (c.estimated ? ' (estimate)' : '')), kpi(st.cleared === run.start ? 'Interest' : st.cleared ? 'Stopped revolving' : 'Still revolving', st.cleared === run.start ? 'none, paid in full' : st.cleared ? short(st.cleared) : 'after the window'), util ? kpi('Utilization before the report', F.percent(util.utilization, { places: 0 }) + (util.warn ? ', over 30%' : '')) : null),
      months.length ? detailTable(['Month', 'Interest'], months.map(ym => ({ cells: [ym, money(st.interestByMonth[ym])] }))) : null,
      h('h3', null, client ? 'Where the payments went' : 'Why it is taking so long'),
      detailTable(['', 'In the window'], [{ cells: ['Paid', money(st.paid)] }, { cells: ['Charged back on', money(st.chargedBack)] }, { cells: ['Interest', money(st.interest)] }, { cells: ['Late fees', money(st.lateFees)] }, { cells: ['Net paydown', money(st.netPaydown)] }]),
      (() => { const w = C.whyStuck(m, run, c.id); return w && w.code !== 'clear' && w.code !== 'float' ? h('p', { class: 'small' }, w.text) : null; })(),
      w ? h('p', { class: 'small' }, 'Annual fee ' + money(w.feeAnnual) + ' against ' + money(w.creditsUsedAnnual + w.rewardsAnnual) + ' of credits and rewards used a year: ' + (w.netAnnual >= 0 ? 'the card pays for itself.' : 'the card costs ' + money(-w.netAnnual) + ' a year net.')) : null,
      client ? null : h('div', { class: 'row' }, h('button', { class: 'btn small', onClick: () => whichCardDrawer(ctx, c) }, 'Which card for a purchase'), h('button', { class: 'btn small', onClick: () => balanceTransferDrawer(ctx, c) }, 'Balance transfer check'), st.revolving ? h('button', { class: 'btn small', onClick: () => solverDrawer(ctx, c) }, 'Pay it off by a date') : null)));
  });
  if (m.extra && (m.extra.cents > 0 || run.extraPaid > 0)) body.appendChild(h('section', { class: 'panel' }, h('h2', null, 'Extra at the debt', h('span', { class: 'tag' }, m.extra.source === 'coach' ? 'set by the coach' : 'from the goal timeline')), h('p', null, money(m.extra.cents) + ' a month on the ' + ordinal(m.extra.day) + ', aimed at the ' + (m.extra.strategy === 'snowball' ? 'smallest balance' : 'highest rate') + (m.extra.stopAtHi ? ', stopping once nothing is above ' + F.percent(m.extra.hiRate, { places: 0 }) : '') + '. ' + money(run.extraPaid) + ' landed in the window.'), run.extraLog.length ? detailTable(['Date', 'To', 'Amount'], run.extraLog.slice(0, 8).map(x => ({ cells: [short(x.date), (m.cards.find(c => c.id === x.to) || m.loans.find(l => l.id === x.to) || { name: x.to }).name, money(x.cents)] }))) : null));
  [].forEach(c => {
  });
}
const kpi = (label, value) => h('div', { class: 'kpi' }, h('div', { class: 'label' }, label), h('div', { class: 'value' }, value));

/* ---- tools (drawers) ---- */
const TOOL_LABELS = { spend: 'Can I spend this?', timing: 'Fix bill timing', shock: 'If income stopped', event: 'A life event', log: 'Log a spend', checkin: 'Weekly check-in', dates: 'Dates and the floor', maybe: 'Maybe money and pay-later' };
const TOOLS = { spend: spendDrawer, timing: timingDrawer, shock: shockDrawer, event: eventDrawer, log: logDrawer, checkin: checkinDrawer, dates: datesDrawer, maybe: maybeDrawer };
function moneyInput(label, value) { return h('input', { class: 'input num', 'aria-label': label, inputmode: 'decimal', value: value === undefined || value === null ? '' : String(value / 100), title: 'Amount' }); }
const centsOf = inp => { const p = parseSaid(inp.value, { defaultCadence: 'month' }); return p && p.cents !== null ? p.cents : null; };

function spendDrawer(ctx) {
  const { app, m, client } = ctx; const amt = moneyInput('How much', 20000); const date = h('input', { type: 'date', class: 'input', 'aria-label': 'When', value: m.start });
  const paid = h('select', { class: 'select', 'aria-label': 'Paid with' }, h('option', { value: 'cash' }, 'Checking'), m.cards.map(c => h('option', { value: c.id }, c.name)));
  const out = h('div', { class: 'calc-result' });
  const run = () => { const cents = centsOf(amt); if (cents === null) return; const r = C.canISpend(m, { cents, date: date.value || m.start, paidWith: paid.value }, { maybeMode: state.maybe }); const words = app.data.calendar.words; clear(out);
    out.appendChild(h('div', { class: 'calc-answer compact' }, h('div', { class: 'calc-answer-big small verdict-' + r.verdict }, r.verdict === 'yes' ? 'Yes' : r.verdict === 'tight' ? 'Tight' : 'Not this time'), h('p', { class: 'read-aloud' }, words[r.verdict])));
    out.appendChild(h('ul', { class: 'small calc-list' }, h('li', null, 'The tightest day goes from ' + money(r.lowBefore.cents) + ' to ' + money(r.lowAfter.cents) + (r.lowAfter.date !== r.lowBefore.date ? ', now ' + short(r.lowAfter.date) : '') + '.'), r.hours !== null ? h('li', null, 'That is ' + F.hours(r.hours) + ' of work at ' + (client ? 'your' : 'the') + ' real hourly wage.') : null, r.interest ? h('li', null, 'About ' + money(r.interest) + ' of interest ' + r.interestNote + '.') : r.interestNote ? h('li', null, r.interestNote + '.') : null, r.delayDays !== null ? h('li', null, 'It pushes the next goal about ' + r.delayDays + (r.delayDays === 1 ? ' day' : ' days') + ' at today’s pace.') : null, r.shortfalls.length ? h('li', null, 'It would leave ' + r.shortfalls.map(s => s.label).join(', ') + ' unpaid.') : null)); };
  [amt, date, paid].forEach(el => el.addEventListener('change', run));
  app.openDrawer(h('div', { class: 'calc-tool' }, h('div', { class: 'calc-fields' }, lab('How much', amt), lab('When', date), lab('Paid with', paid)), h('button', { class: 'btn primary', onClick: run }, 'Check'), out), { label: 'Can I spend this', title: 'Can I spend this?' });
  run();
}
const lab = (label, control) => h('div', { class: 'calc-field' }, h('label', null, label), h('div', { class: 'calc-control' }, control));
function timingDrawer(ctx, redraw) {
  const { app, m } = ctx; const fx = C.billTimingFixes(m, { maybeMode: state.maybe });
  const body = h('div', { class: 'calc-tool' }, h('p', { class: 'small muted' }, 'Due dates a client can usually move: card payments and utilities. Each move is re-run day by day; these raise the lowest point most.'));
  if (!fx.fixes.length) body.appendChild(h('p', null, 'No due-date move raises the lowest point (' + money(fx.base.low.cents) + ' on ' + short(fx.base.low.date) + '). The timing is already as good as a move can make it.'));
  fx.fixes.forEach(f => body.appendChild(h('section', { class: 'panel fix' }, h('h3', null, f.label + ': from the ' + f.from + ' to the ' + f.to), h('p', null, 'Lowest point ' + money(f.lowBefore.cents) + ' becomes ' + money(f.lowAfter.cents) + ' (' + money(f.gain) + ' higher)' + (f.shortfallsAfter < f.shortfallsBefore ? ', and ' + (f.shortfallsBefore - f.shortfallsAfter) + ' fewer bills go unpaid' : '') + '.'), h('p', { class: 'small script' }, '“' + f.script + '”'), h('button', { class: 'btn small primary', onClick: () => { app.change(rec => C.setCalendar(rec, cal => { if (f.kind === 'card') { cal.cards[f.id] = Object.assign({}, cal.cards[f.id] || {}, { dueDay: f.to, stmtDay: ((f.to - (m.cards.find(c => c.id === f.id) || { graceDays: 24 }).graceDays - 1 + 62) % 31) + 1 }); } else cal.dueDays[f.id] = f.to; }, { session: app.session }), { reason: 'calendar' }); app.toast(f.label + ' now due on the ' + f.to + '. Make the call to the issuer.'); closeOverlay(); redraw(); } }, 'Plan this move'))));
  app.openDrawer(body, { label: 'Bill timing', title: 'Fix bill timing' });
}
function shockDrawer(ctx) {
  const { app, m } = ctx; const months = h('input', { class: 'input num', type: 'number', min: '1', max: '24', value: '3', 'aria-label': 'Months without income' }); const from = h('input', { type: 'date', class: 'input', value: m.start, 'aria-label': 'From' }); const out = h('div');
  const run = () => { const r = C.incomeShock(m, { from: from.value || m.start, months: +months.value || 3 }, { maybeMode: state.maybe }); clear(out); out.appendChild(h('div', { class: 'calc-answer compact' }, h('div', { class: 'calc-answer-big small' }, r.runwayDays === null ? 'The cash holds' : r.runwayDays + ' days'), h('p', { class: 'read-aloud' }, r.runwayDays === null ? 'With income paused for ' + r.months + ' months the checking account never goes under the floor in this window.' : 'With income paused from ' + short(r.from) + ', checking goes under the floor on ' + short(r.firstBad) + '.'))); if (r.atRisk.length) out.appendChild(h('div', null, h('h3', null, 'Bills at risk first'), detailTable(['Bill', 'Date', 'Amount'], r.atRisk.map(b => ({ cells: [b.label, short(b.date), money(b.cents)] }))))); };
  [months, from].forEach(el => el.addEventListener('change', run));
  app.openDrawer(h('div', { class: 'calc-tool' }, h('div', { class: 'calc-fields' }, lab('From', from), lab('Months without income', months)), out), { label: 'Income shock', title: 'If income stopped' }); run();
}
function eventDrawer(ctx, redraw) {
  const { app, m } = ctx; const T = app.data.lifeEvents.templates; const sel = h('select', { class: 'select', 'aria-label': 'Life event' }, T.map(t => h('option', { value: t.id }, t.label))); const date = h('input', { type: 'date', class: 'input', value: m.start, 'aria-label': 'When it happens' }); const out = h('div'); let items = [];
  const preview = () => { const t = T.find(x => x.id === sel.value); items = C.lifeEventItems(t, date.value || m.start); clear(out); out.appendChild(h('p', { class: 'small' }, t.summary)); out.appendChild(detailTable(['Item', 'Date', 'Amount', 'Repeats'], items.map(it => ({ cells: [it.label, short(it.date), (it.direction === 'in' ? '+' : '') + money(it.cents), it.cadence === 'once' ? 'once' : it.cadence + (it.count ? ' x ' + it.count : '') + (it.likelihood ? ', ' + Math.round(it.likelihood * 100) + '% likely' : '')] })))); out.appendChild(h('p', { class: 'small muted' }, 'Nothing is written until you confirm; edit the amounts after in Dates and the floor.')); out.appendChild(h('button', { class: 'btn primary', onClick: () => { app.change(rec => C.setCalendar(rec, cal => { cal.extras = (cal.extras || []).concat(items.map(it => ({ id: it.id, label: it.label, cents: it.cents, direction: it.direction, cadence: it.cadence === 'once' ? 'once' : it.cadence, date: it.date, day: it.day, anchor: it.anchor, from: it.from, count: it.count, template: it.template }))); }, { session: app.session }), { reason: 'calendar' }); app.toast(t.label + ' added to the calendar.'); closeOverlay(); redraw(); } }, 'Confirm: put these on the calendar')); };
  sel.addEventListener('change', preview); date.addEventListener('change', preview);
  app.openDrawer(h('div', { class: 'calc-tool' }, h('div', { class: 'calc-fields' }, lab('Event', sel), lab('When', date)), out), { label: 'Life event', title: 'A life event' }); preview();
}
function logDrawer(ctx, redraw) {
  const { app, m } = ctx; const cal = C.calendarOf(app.record); const tags = app.data.calendar.spendLogger.tags;
  const amt = moneyInput('Amount'); const what = h('input', { class: 'input', 'aria-label': 'What', title: 'What' }); const tag = h('select', { class: 'select', 'aria-label': 'Tag' }, tags.map(t => h('option', { value: t }, t))); const paid = h('select', { class: 'select', 'aria-label': 'Paid with' }, h('option', { value: 'cash' }, 'Checking'), m.cards.map(c => h('option', { value: c.id }, c.name)));
  const amt2 = moneyInput('Second part'); const tag2 = h('select', { class: 'select', 'aria-label': 'Second tag' }, h('option', { value: '' }, 'No split'), tags.map(t => h('option', { value: t }, t)));
  const pace = h('div');
  const drawPace = () => { clear(pace); const rows = C.spendPace(m, app.result, C.calendarOf(app.record), m.start); pace.appendChild(h('h3', null, 'This month, by tag')); pace.appendChild(detailTable(['Tag', 'Budget', 'Spent', 'Left', 'A day to stay inside', 'Last month by today'], rows.map(r => ({ cls: r.hot ? 'is-low' : '', cells: [r.tag + (r.hot ? ' (running hot)' : ''), money(r.budget), money(r.spent), money(r.left), money(r.perDay), money(r.lastBySameDay)] })))); pace.appendChild(h('p', { class: 'small muted' }, 'Budgets are the Ledger lines by area; spent is what has been logged here this month.')); };
  const save = () => { const c = centsOf(amt); if (c === null) { app.toast('An amount first.'); return; } const parts = [{ cents: c, tag: tag.value }]; const c2 = centsOf(amt2); if (tag2.value && c2) { parts[0].cents = Math.max(0, c - c2); parts.push({ cents: c2, tag: tag2.value }); } app.change(rec => C.setCalendar(rec, cl => { parts.forEach(p => cl.logs.push({ id: C.newId('log'), ts: new Date().toISOString(), date: m.start, cents: p.cents, what: what.value.trim() || p.tag, tag: p.tag, paidWith: paid.value })); }, { session: app.session }), { reason: 'calendar' }); amt.value = ''; what.value = ''; amt2.value = ''; app.toast('Logged. Safe to spend updated.'); drawPace(); redraw(); };
  amt.addEventListener('keydown', e => { if (e.key === 'Enter') save(); });
  app.openDrawer(h('div', { class: 'calc-tool' }, h('div', { class: 'calc-fields' }, lab('Amount', amt), lab('What', what), lab('Tag', tag), lab('Paid with', paid), lab('Split: second part', amt2), lab('Second tag', tag2)), h('button', { class: 'btn primary', onClick: save }, 'Log it'), h('p', { class: 'small muted' }, (cal.logs || []).length + ' logged so far.'), pace), { label: 'Spend logger', title: 'Log a spend' }); drawPace(); setTimeout(() => amt.focus(), 0);
}
function checkinDrawer(ctx, redraw) {
  const { app, m, run } = ctx; const cal = C.calendarOf(app.record); const last = cal.checkins.length ? cal.checkins[cal.checkins.length - 1] : null; const since = last ? last.date : C.addDays(m.start, -7);
  const base = C.simulate(Object.assign({}, m, { start: since, days: C.daysBetween(since, m.start) + 1 }), { maybeMode: state.maybe });
  const due = C.dueSince(base, since, m.start); const choices = {};
  const list = due.length ? h('div', { class: 'tablewrap' }, h('table', { class: 'data calc-table' }, h('thead', null, h('tr', null, h('th', null, 'Since ' + short(since)), h('th', { class: 'num' }, 'Amount'), h('th', null, 'What happened'))), h('tbody', null, due.map((e, i) => { const sel = h('select', { class: 'select', 'aria-label': 'What happened with ' + e.label, onChange: ev => { choices[i] = ev.target.value; } }, h('option', { value: 'happened' }, 'Happened'), h('option', { value: 'different' }, 'Different amount'), h('option', { value: 'skipped' }, 'Did not happen')); const diff = moneyInput('Actual amount for ' + e.label, Math.abs(e.cents)); diff.addEventListener('change', () => { choices[i] = 'different:' + centsOf(diff); }); return h('tr', null, h('td', { class: 'wrap' }, short(e.date) + ' ' + e.label), h('td', { class: 'num' }, money(Math.abs(e.cents))), h('td', null, h('div', { class: 'row' }, sel, diff))); })))) : h('p', { class: 'muted small' }, 'Nothing was due since ' + short(since) + '.');
  const balInputs = m.accounts.map(a => ({ a, inp: moneyInput('Balance of ' + a.name, run.days[0].balances[a.id]) }));
  const drift = C.drift(cal.checkins);
  const save = () => { const actual = {}, forecast = {}; balInputs.forEach(({ a, inp }) => { const c = centsOf(inp); actual[a.id] = c === null ? run.days[0].balances[a.id] : c; forecast[a.id] = run.days[0].balances[a.id]; });
    app.change(rec => { C.setCalendar(rec, cl => { cl.checkins.push({ ts: new Date().toISOString(), date: m.start, since, forecast, actual }); due.forEach((e, i) => { const ch = choices[i]; if (!ch || ch === 'happened') return; const it = run.items.find(x => x.label === e.label && x.date === e.date) || base.items.find(x => x.label === e.label && x.date === e.date); if (!it) return; if (ch === 'skipped') cl.overrides[it.sourceId + '|' + it.origDate] = { skip: true }; else if (ch.startsWith('different:')) { const c = +ch.split(':')[1]; if (c) cl.overrides[it.sourceId + '|' + it.origDate] = { cents: c }; } }); }, { session: app.session }); return true; }, { reason: 'calendar' });
    balInputs.forEach(({ a }) => { if (actual[a.id] !== forecast[a.id]) app.setFieldWhy(a.id, 'accountBalance', actual[a.id], 'known', 'client', null, 'move'); });
    app.toast('Checked in. The calendar starts again from today’s balances.'); closeOverlay(); redraw(); };
  app.openDrawer(h('div', { class: 'calc-tool' }, list, h('h3', null, 'Real balances today', h('span', { class: 'tag' }, 'prefilled with the forecast')), h('div', { class: 'calc-fields' }, balInputs.map(({ a, inp }) => lab(a.name, inp))), drift.kind === 'bias' ? h('p', { class: 'small' }, 'Across ' + drift.count + ' check-ins you land about ' + money(Math.abs(drift.mean)) + (drift.mean < 0 ? ' below' : ' above') + ' the forecast almost every time: a steady lean, worth fixing in the amounts.') : drift.kind === 'noise' ? h('p', { class: 'small' }, 'Across ' + drift.count + ' check-ins the misses go both ways (about ' + money(drift.sd) + ' either side): noise, not a lean.') : null, h('button', { class: 'btn primary', onClick: save }, 'Save the check-in')), { label: 'Weekly check-in', title: 'Weekly check-in' });
}
function datesDrawer(ctx, redraw) {
  const { app, m } = ctx; const cal = C.calendarOf(app.record); const P = app.record.planets; const nameOf = id => { for (const p of Object.keys(P)) { const r = P[p].rows.find(x => x.id === id); if (r) return r.nickname || r.type; } return id; };
  const set = fn => app.change(rec => C.setCalendar(rec, fn, { session: app.session }), { reason: 'calendar', silent: true });
  const body = h('div', { class: 'calc-tool' });
  body.appendChild(h('h3', null, 'Paydays', h('span', { class: 'tag' }, 'the next payday for each income')));
  m.incomes.filter(i => i.source !== 'reimb' && i.source !== 'imported').forEach(i => { const inp = h('input', { type: 'date', class: 'input', value: i.anchor, 'aria-label': 'Next payday for ' + i.label, onChange: e => { set(c => { c.anchor[i.id] = e.target.value; }); redraw(); } }); body.appendChild(lab(i.label + ' (' + i.cadence + ')', inp)); });
  if (m.incomes.some(i => i.source === 'imported')) body.appendChild(h('p', { class: 'small muted' }, 'Paydays come from the imported transactions; they win over the cadence.'));
  body.appendChild(h('h3', null, 'Bills', h('span', { class: 'tag' }, 'day of the month; blank spreads the line across the month')));
  P.spending.rows.filter(r => r.type === 'line' || r.type === 'other' || r.type === 'savings').forEach(r => { const cur = cal.dueDays[r.id]; const inp = h('input', { type: 'number', class: 'input num', min: '1', max: '31', value: typeof cur === 'number' ? String(cur) : '', title: 'spread', 'aria-label': 'Due day for ' + (r.nickname || r.type), onChange: e => { set(c => { if (e.target.value) c.dueDays[r.id] = Math.max(1, Math.min(31, +e.target.value)); else delete c.dueDays[r.id]; }); redraw(); } }); const mv = h('label', { class: 'small' }, h('input', { type: 'checkbox', checked: !!cal.movable[r.id], onChange: e => { set(c => { if (e.target.checked) c.movable[r.id] = true; else delete c.movable[r.id]; }); } }), ' movable'); body.appendChild(h('div', { class: 'calc-field' }, h('label', null, r.nickname || r.type), h('div', { class: 'calc-control row' }, inp, mv))); });
  body.appendChild(h('h3', null, 'Cards', h('span', { class: 'tag' }, 'statement day and due day')));
  m.cards.forEach(c => { const s = h('input', { type: 'number', class: 'input num', min: '1', max: '31', value: String(c.stmtDay), 'aria-label': 'Statement day for ' + c.name, onChange: e => { set(cl => { cl.cards[c.id] = Object.assign({}, cl.cards[c.id] || {}, { stmtDay: +e.target.value || 15 }); }); redraw(); } }); const d = h('input', { type: 'number', class: 'input num', min: '1', max: '31', value: c.dueDay ? String(c.dueDay) : '', title: c.graceDays + ' days later', 'aria-label': 'Due day for ' + c.name, onChange: e => { set(cl => { cl.cards[c.id] = Object.assign({}, cl.cards[c.id] || {}, { dueDay: e.target.value ? +e.target.value : null }); }); redraw(); } }); const flat = h('label', { class: 'small' }, h('input', { type: 'checkbox', checked: c.goalNoInterest, onChange: e => { set(cl => { cl.cards[c.id] = Object.assign({}, cl.cards[c.id] || {}, { goalNoInterest: e.target.checked }); }); redraw(); } }), ' everyday card, hold it flat'); body.appendChild(h('div', { class: 'calc-field' }, h('label', null, c.name), h('div', { class: 'calc-control row' }, h('span', { class: 'small muted' }, 'closes'), s, h('span', { class: 'small muted' }, 'due'), d, flat))); });
  if (m.loans.length) { body.appendChild(h('h3', null, 'Loans', h('span', { class: 'tag' }, 'payment day'))); m.loans.forEach(l => body.appendChild(lab(l.name, h('input', { type: 'number', class: 'input num', min: '1', max: '31', value: String(l.day), 'aria-label': 'Payment day for ' + l.name, onChange: e => { set(c => { c.dueDays[l.id] = +e.target.value || 1; }); redraw(); } })))); }
  body.appendChild(h('h3', null, 'Extra at the debt', h('span', { class: 'tag' }, m.extra.source === 'coach' ? 'set here' : m.extra.source === 'goal-plan' ? 'from the goal timeline until you set it' : 'none yet')));
  const exAmt = moneyInput('Extra a month', m.extra.cents); exAmt.addEventListener('change', () => { const c = centsOf(exAmt); set(cl => { cl.extra = Object.assign({}, cl.extra || {}, { cents: c === null ? 0 : c }); }); redraw(); });
  const exDay = h('input', { type: 'number', class: 'input num', min: '1', max: '28', value: String(m.extra.day), 'aria-label': 'Extra payment day', onChange: e => { set(cl => { cl.extra = Object.assign({}, cl.extra || {}, { day: Math.max(1, Math.min(28, +e.target.value || 14)) }); }); redraw(); } });
  const exStrat = h('select', { class: 'select', 'aria-label': 'Aim the extra', onChange: e => { set(cl => { cl.extra = Object.assign({}, cl.extra || {}, { strategy: e.target.value }); }); redraw(); } }, [['avalanche', 'Highest rate first'], ['snowball', 'Smallest balance first']].map(o => h('option', { value: o[0], selected: m.extra.strategy === o[0] }, o[1])));
  body.appendChild(lab('Extra a month', exAmt)); body.appendChild(lab('On the day', exDay)); body.appendChild(lab('Aimed at', exStrat));
  body.appendChild(lab('Stop at the high rate', h('label', { class: 'calc-switch' }, h('input', { type: 'checkbox', checked: m.extra.stopAtHi, onChange: e => { set(cl => { cl.extra = Object.assign({}, cl.extra || {}, { stopAtHi: e.target.checked }); }); redraw(); } }), h('span', null, 'Once every debt at or above ' + F.percent(m.extra.hiRate, { places: 0 }) + ' is clear, the extra becomes surplus for the goals'))));
  body.appendChild(h('p', { class: 'small muted' }, 'Student loans and the everyday card wait while anything else is open. A finished pay-later plan rolls its installment into the extra.'));
  body.appendChild(h('h3', null, 'Spending on a card you already budget for', h('span', { class: 'tag' }, 'paid with the minimum, so it never becomes debt')));
  m.bills.filter(b => b.paidWith !== 'cash').forEach(b => body.appendChild(lab(b.label, h('label', { class: 'calc-switch' }, h('input', { type: 'checkbox', checked: !!b.budgeted, onChange: e => { set(cl => { if (e.target.checked) cl.budgeted[b.id] = true; else delete cl.budgeted[b.id]; }); redraw(); } }), h('span', null, b.budgeted ? 'Budgeted: the payment covers it' : 'Not marked')))));
  body.appendChild(h('h3', null, 'The floor and the rules'));
  const floorSel = h('select', { class: 'select', 'aria-label': 'Floor', onChange: e => { set(c => { c.floorMode = e.target.value; }); redraw(); } }, [['lean', 'The lean month step, when funded'], ['zero', 'Zero'], ['fixed', 'A fixed amount']].map(o => h('option', { value: o[0], selected: cal.floorMode === o[0] }, o[1])));
  const fixed = moneyInput('Fixed floor', cal.floorCents || 0); fixed.addEventListener('change', () => { const c = centsOf(fixed); set(cl => { cl.floorCents = c; cl.floorMode = 'fixed'; }); redraw(); });
  body.appendChild(lab('Floor', floorSel)); body.appendChild(lab('Fixed floor amount', fixed));
  body.appendChild(lab('Guard', h('label', { class: 'calc-switch' }, h('input', { type: 'checkbox', checked: cal.guard !== false, onChange: e => { set(c => { c.guard = e.target.checked; }); redraw(); } }), h('span', null, 'Planned payments that would break the floor are not made; they are listed as shortfalls'))));
  body.appendChild(lab('Month-end sweep', h('label', { class: 'calc-switch' }, h('input', { type: 'checkbox', checked: !!cal.sweep, onChange: e => { set(c => { c.sweep = e.target.checked; }); redraw(); } }), h('span', null, 'What is left above the floor at month end goes to the next goal'))));
  body.appendChild(lab('Maybe money counted', h('select', { class: 'select', 'aria-label': 'Maybe money', onChange: e => { state.maybe = e.target.value; redraw(); } }, [['ignore', 'Ignore it'], ['likely', 'Likely only (60% and up)'], ['weighted', 'Weighted by likelihood']].map(o => h('option', { value: o[0], selected: state.maybe === o[0] }, o[1])))));
  if (Object.keys(cal.overrides).length) body.appendChild(h('p', { class: 'small' }, Object.keys(cal.overrides).length + ' one-off moves or skips. ', h('button', { class: 'linklike small', onClick: () => { set(c => { c.overrides = {}; }); closeOverlay(); redraw(); } }, 'Clear them')));
  if ((cal.extras || []).length) body.appendChild(h('p', { class: 'small' }, (cal.extras || []).length + ' life event items on the calendar. ', h('button', { class: 'linklike small', onClick: () => { set(c => { c.extras = []; }); closeOverlay(); redraw(); } }, 'Remove them')));
  app.openDrawer(body, { label: 'Dates and the floor', title: 'Dates and the floor' });
}
function maybeDrawer(ctx, redraw) {
  const { app, m } = ctx; const cal = C.calendarOf(app.record); const set = fn => app.change(rec => C.setCalendar(rec, fn, { session: app.session }), { reason: 'calendar', silent: true });
  const body = h('div', { class: 'calc-tool' });
  body.appendChild(h('h3', null, 'Maybe money', h('span', { class: 'tag' }, 'dated, with a likelihood')));
  if (cal.maybe.length) body.appendChild(detailTable(['Item', 'Date', 'Amount', 'Likely'], cal.maybe.map(x => ({ cells: [x.label, short(x.date), (x.direction === 'in' ? '+' : '-') + money(x.cents), Math.round((x.likelihood || 0.5) * 100) + '% ' , h('button', { class: 'btn small quiet', onClick: () => { set(c => { c.maybe = c.maybe.filter(y => y.id !== x.id); }); closeOverlay(); redraw(); } }, 'Remove')] }))));
  const ml = h('input', { class: 'input', title: 'What', 'aria-label': 'Maybe item' }); const ma = moneyInput('Maybe amount'); const md = h('input', { type: 'date', class: 'input', value: C.addDays(m.start, 14), 'aria-label': 'Maybe date' }); const mp = h('input', { type: 'number', class: 'input num', min: '0', max: '100', value: '60', 'aria-label': 'Likelihood percent' }); const dir = h('select', { class: 'select', 'aria-label': 'Direction' }, h('option', { value: 'in' }, 'Coming in'), h('option', { value: 'out' }, 'Going out'));
  body.appendChild(h('div', { class: 'calc-fields' }, lab('What', ml), lab('Amount', ma), lab('Date', md), lab('Likelihood %', mp), lab('Direction', dir)));
  body.appendChild(h('button', { class: 'btn', onClick: () => { const c = centsOf(ma); if (!ml.value.trim() || c === null) { app.toast('A name and an amount first.'); return; } set(cl => { cl.maybe.push({ id: C.newId('mb'), label: ml.value.trim(), cents: c, date: md.value, likelihood: Math.max(0, Math.min(1, (+mp.value || 50) / 100)), direction: dir.value }); }); closeOverlay(); redraw(); } }, 'Add maybe money'));
  body.appendChild(h('h3', null, 'Pay-later plans', h('span', { class: 'tag' }, 'each installment on its date, counted as debt')));
  if (cal.payLater.length) body.appendChild(detailTable(['Plan', 'Total', 'Each', 'Next', 'Left'], cal.payLater.map(p => ({ cells: [p.label, money(p.total), money(p.installment), short(p.nextDate), money(Math.max(0, p.total - (p.paid || 0))), h('button', { class: 'btn small quiet', onClick: () => { set(c => { c.payLater = c.payLater.filter(y => y.id !== p.id); }); closeOverlay(); redraw(); } }, 'Remove')] }))));
  const pl = h('input', { class: 'input', title: 'What', 'aria-label': 'Pay-later plan' }); const pt = moneyInput('Total'); const pi = moneyInput('Each installment'); const pn = h('input', { type: 'date', class: 'input', value: C.addDays(m.start, 7), 'aria-label': 'Next installment date' }); const pf = h('select', { class: 'select', 'aria-label': 'Frequency' }, h('option', { value: 'biweekly' }, 'Every two weeks'), h('option', { value: 'monthly' }, 'Monthly'), h('option', { value: 'weekly' }, 'Weekly')); const pp = moneyInput('Paid so far', 0);
  body.appendChild(h('div', { class: 'calc-fields' }, lab('Plan', pl), lab('Total', pt), lab('Each installment', pi), lab('Next date', pn), lab('Frequency', pf), lab('Paid so far', pp)));
  body.appendChild(h('button', { class: 'btn', onClick: () => { const t = centsOf(pt), i = centsOf(pi); if (!pl.value.trim() || t === null || i === null) { app.toast('A name, a total and an installment first.'); return; } set(cl => { cl.payLater.push({ id: C.newId('pl'), label: pl.value.trim(), total: t, installment: i, nextDate: pn.value, freq: pf.value, paid: centsOf(pp) || 0 }); }); closeOverlay(); redraw(); } }, 'Add the plan'));
  app.openDrawer(body, { label: 'Maybe money and pay-later', title: 'Maybe money and pay-later' });
}
function whichCardDrawer(ctx, card) {
  const { app, m, run } = ctx; const amt = moneyInput('Amount', 12000); const cat = h('select', { class: 'select', 'aria-label': 'Category' }, ['dining', 'groceries', 'travel', 'gas', 'streaming', 'other'].map(c => h('option', { value: c }, c))); const out = h('div');
  const go = () => { const c = centsOf(amt); if (c === null) return; const rows = C.whichCard(m, run, { cents: c, category: cat.value }, app.data.cards); clear(out); out.appendChild(detailTable(['Card', 'Rewards', 'Interest if carried', 'Net', 'Interest-free days'], rows.map(r => ({ cls: r === rows[0] ? 'is-pick' : '', cells: [r.name + (r.utilizationWarn ? ' (over 30% before the report)' : ''), money(r.rewards), money(r.interest), money(r.net), r.interestFreeDays ? String(r.interestFreeDays) : (r.revolving ? 'none, it is revolving' : '')] })))); out.appendChild(h('p', { class: 'small muted' }, 'Rewards from the card library at its point value; interest for one month at the card’s rate when it is carrying a balance.')); };
  [amt, cat].forEach(e => e.addEventListener('change', go));
  app.openDrawer(h('div', { class: 'calc-tool' }, h('div', { class: 'calc-fields' }, lab('Purchase', amt), lab('Category', cat)), out), { label: 'Which card', title: 'Which card for a purchase' }); go();
}
function balanceTransferDrawer(ctx, card) {
  const { app } = ctx; const fee = h('input', { type: 'number', class: 'input num', value: '3', min: '0', max: '6', step: '0.5', 'aria-label': 'Transfer fee percent' }); const months = h('input', { type: 'number', class: 'input num', value: '18', min: '6', max: '24', 'aria-label': 'Promo months' }); const post = h('input', { type: 'number', class: 'input num', value: String(Math.round(card.apr * 1000) / 10), 'aria-label': 'Rate after the promo' }); const pay = moneyInput('Monthly payment', Math.max(card.minimum || 0, Math.round(card.balance / 18))); const out = h('div');
  const go = () => { const r = C.balanceTransfer({ balance: card.balance, apr: card.apr, feeShare: (+fee.value || 0) / 100, promoMonths: +months.value || 18, postApr: (+post.value || 0) / 100, payment: centsOf(pay) || 0 }); clear(out); out.appendChild(h('div', { class: 'calc-answer compact' }, h('div', { class: 'calc-answer-big small' }, r.worthIt ? 'Worth it' : 'Not worth it'), h('p', { class: 'read-aloud' }, 'Skipping ' + money(r.interestSkipped) + ' of interest over ' + r.months + ' months against a fee of ' + money(r.fee) + (r.balanceLeftAfterPromo ? ', with ' + money(r.balanceLeftAfterPromo) + ' still owed when the promo ends' : ', and the balance gone before the promo ends') + '.'))); };
  [fee, months, post, pay].forEach(e => e.addEventListener('change', go));
  app.openDrawer(h('div', { class: 'calc-tool' }, h('p', { class: 'small muted' }, card.name + ': ' + money(card.balance) + ' at ' + F.percent(card.apr, { places: 2 }) + '.'), h('div', { class: 'calc-fields' }, lab('Transfer fee %', fee), lab('0% months', months), lab('Rate after %', post), lab('Payment a month', pay)), out), { label: 'Balance transfer', title: 'Balance transfer check' }); go();
}
function solverDrawer(ctx, card) {
  const { app, m } = ctx; const by = h('input', { type: 'date', class: 'input', value: C.addDays(m.start, 365), 'aria-label': 'Paid off by' }); const which = h('select', { class: 'select', 'aria-label': 'Which debt' }, h('option', { value: card.id }, card.name), h('option', { value: 'all' }, 'Every card and loan')); const out = h('div');
  const go = () => { clear(out); const r = C.solvePayoff(m, which.value, by.value, { maybeMode: state.maybe }); out.appendChild(h('div', { class: 'calc-answer compact' }, h('div', { class: 'calc-answer-big small' }, r.already ? 'Already on track' : r.impossible ? 'Not by then' : money(r.need) + ' a month'), h('p', { class: 'read-aloud' }, r.already ? 'At today\u2019s pace it clears by ' + short(r.date) + '.' : r.impossible ? 'Even ' + money(60000) + ' a month more does not clear it by ' + short(by.value) + (r.best ? '; the best is ' + short(r.best) : '') + '.' : money(r.need) + ' a month more, aimed at it on the ' + ordinal(m.extra.day) + ', clears it by ' + short(r.date) + '.' + (r.breaksCash ? ' That breaks the cash floor on ' + r.shortfalls + (r.shortfalls === 1 ? ' day' : ' days') + '; move a due date or lower the amount.' : ' The cash holds.')))); if (!r.already && !r.impossible) out.appendChild(h('button', { class: 'btn primary', onClick: () => { app.change(rec => C.setCalendar(rec, cl => { cl.extra = Object.assign({}, cl.extra || {}, { cents: r.need, stopAtHi: false }); }, { session: app.session }), { reason: 'calendar' }); app.toast('Extra set to ' + money(r.need) + ' a month.'); closeOverlay(); ctx.redraw ? ctx.redraw() : app.rerender(); } }, 'Make that the extra')); };
  [by, which].forEach(e => e.addEventListener('change', go));
  app.openDrawer(h('div', { class: 'calc-tool' }, h('div', { class: 'calc-fields' }, lab('Paid off by', by), lab('Which', which)), out), { label: 'Pay it off by', title: 'Pay it off by a date' }); go();
}
