import { chromium, devices } from '@playwright/test';
const out = process.argv[2] ?? '.';
const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_PATH || undefined });
const ctx = await browser.newContext({ ...devices['Pixel 7'], colorScheme: 'light' });
const page = await ctx.newPage();
const shot = (name) => page.screenshot({ path: `${out}/${name}.png`, fullPage: true });
const go = async (p) => { await page.goto(`http://127.0.0.1:4173/#/${p}`); await page.getByTestId('hide').waitFor(); await page.waitForTimeout(300); };
await go('demo'); await page.getByTestId('sample-sample-inperson').click(); await page.getByTestId('today-numbers').waitFor();
await go('businesses/sample-inperson-inPerson'); await page.getByTestId('in-bookingRate').fill(''); await page.getByTestId('in-bookingRate').blur(); await page.waitForTimeout(300); await shot('p4-tab-missing');
await go('numbers'); await page.waitForTimeout(300); await shot('p4-numbers-missing');
await go('toolbox'); await shot('p4-toolbox');
await ctx.close(); await browser.close();
console.log('done');
