/* The ten calculator charts (Level 13, MR-067). Same contract as the other
   chart builders: read the computed result (and the record behind it) and
   return plain numbers for ui/charts-calc.js to draw, or { needs } when the
   inputs are missing. The calculators' own inputs come from
   engine/calculators.js, so a chart on Measure shows the same picture the
   calculator screen does. */
import { buildModel, simulate, yearStrip as strip } from './cashcal.js';
import { runHome, runHouse, runCar, runRetire } from './calculators.js';
import { rentVsBuyRange } from './house.js';

const need = list => ({ needs: list });
const CAL_NEEDS = ['a checking account balance and an income'];
function modelOf(result, days) { const rec = result.record; const data = result.data; if (!rec || !data) return null; const m = buildModel(rec, result, data, { days }); return m.accounts.length && m.incomes.length ? m : null; }
export function calendarBalance(result) { const m = modelOf(result, 60); if (!m) return need(CAL_NEEDS); const run = simulate(m); return { days: run.days.map(d => ({ date: d.date, cents: d.primary })), floor: m.floor, floorSource: m.floorSource, low: run.low, safe: run.safeToSpend.today, nextIncome: run.safeToSpend.nextIncome, shortfalls: run.shortfalls.length, estimated: m.incomes.some(i => i.estimated) || m.bills.some(b => b.estimated) }; }
export function paycheckMap(result) { const m = modelOf(result, 60); if (!m) return need(CAL_NEEDS); const run = simulate(m); if (!run.paychecks.length) return need(CAL_NEEDS); return { paychecks: run.paychecks.slice(0, 6).map(p => ({ date: p.date, label: p.label, cents: p.cents, left: p.left, bills: p.bills.slice().sort((a, b) => b.cents - a.cents).slice(0, 6).concat(p.bills.length > 6 ? [{ label: 'Everything else', cents: p.bills.slice().sort((a, b) => b.cents - a.cents).slice(6).reduce((s, b) => s + b.cents, 0) }] : []) })) }; }
export function yearStrip(result) { const m = modelOf(result, 366); if (!m) return need(CAL_NEEDS); const y = strip(m); return { months: y.months.slice(0, 12), floor: y.floor, everydayWeek: Math.round(m.everydayMonthly * 7 / 30.44) }; }
function home(result) { const rec = result.record; const data = result.data; if (!rec || !data) return null; const H = runHome(rec, result, data); return H.out.needs ? null : H; }
export function homeAnswers(result) { const H = home(result); if (!H) return need(['gross pay and take-home pay']); const o = H.out; const bars = [{ id: 'lender', label: 'A lender might approve', price: o.lender.price, monthly: o.lender.cost.total, note: (o.lender.binding === 'front' ? 'housing share of gross' : 'all-debt share of gross') + ' binds' }, { id: 'comfortable', label: 'Comfortable', price: o.comfortable.price, monthly: o.comfortable.cost.total, note: Math.round(o.comfortable.share * 100) + '% of take-home, maintenance included' }]; if (o.fiSafe) bars.push({ id: 'fi', label: 'Keeps the FI date', price: o.fiSafe.price, monthly: o.fiSafe.cost ? o.fiSafe.cost.total : 0, note: 'moves it ' + o.fiSafe.allowed + ' months at most' }); return { bars, share: o.comfortable.share, takeHome: H.inp.takeHomeMonthly, rentNow: H.inp.rentNow }; }
export function downPaymentLadder(result) { const H = home(result); if (!H) return need(['gross pay and take-home pay']); return { rungs: H.out.ladder.map(l => ({ downPct: l.downPct, price: l.price, cashToClose: l.cashToClose, months: l.months, mi: l.mi })), cash: H.inp.cashAvailable, pace: H.inp.savingsPaceMonthly }; }
function house(result) { const rec = result.record; const data = result.data; if (!rec || !data || !home(result)) return null; const Hs = runHouse(rec, result, data); return Hs.own ? Hs : null; }
export function rentVsBuy(result) { const Hs = house(result); if (!Hs) return need(['gross pay and take-home pay']); const inp = Hs.inp; if (!(inp.rentNow > 0)) return need(['spending lines for housing, food or transportation']); const r = rentVsBuyRange(result.data.housingCosts, inp, { years: 30, rentMonthly: inp.rentNow, rentGrowth: inp.rentGrowth, rentersInsuranceMonthly: inp.rentersInsuranceMonthly, securityDepositMonths: inp.securityDepositMonths, stockReturn: inp.stockReturn, capitalGainsRate: inp.capitalGainsRate, appreciation: inp.appreciation }); return { years: r.likely.years.map((y, i) => ({ year: y.year, buyer: y.buyerNetWorth, renter: y.renterNetWorth, buyerLow: r.low.years[i].buyerNetWorth, buyerHigh: r.high.years[i].buyerNetWorth })), breakEven: r.likely.breakEvenYear, stay: inp.years, price: inp.price, rent: inp.rentNow }; }
export function equityVsLoan(result) { const Hs = house(result); if (!Hs) return need(['gross pay and take-home pay']); const own = Hs.own; return { years: own.years.map(y => ({ year: y.year, value: y.value, balance: y.balance, equity: y.equity })), miEndsMonth: own.miEndsMonth, price: Hs.inp.price, loan: own.first.loan }; }
function car(result) { const rec = result.record; const data = result.data; if (!rec || !data) return null; const C = runCar(rec, result, data, false); return C.out.options.length && C.inp.grossMonthly > 0 ? C : null; }
export function carTco(result) { const C = car(result); if (!C) return need(['gross pay and take-home pay']); return { options: C.out.options.map(o => ({ kind: o.kind, label: o.label, stack: o.stack, total: o.totalCost, perMonth: o.costPerMonth, perMile: o.costPerMile })), cheapest: C.out.cheapest, years: C.inp.keepYears, nowMonthly: C.inp.transportNowMonthly }; }
export function carValueVsLoan(result) { const C = car(result); if (!C) return need(['gross pay and take-home pay']); const opts = C.out.options.filter(o => o.schedule); if (!opts.length) return need(['gross pay and take-home pay']); return { options: opts.map(o => ({ kind: o.kind, label: o.label, values: o.values, balances: o.schedule, underwater: o.underwaterMonths, worstGap: o.worstGap })), years: C.inp.keepYears }; }
export function retireGrowth(result) { const rec = result.record; const data = result.data; if (!rec || !data) return need(['an age, a retirement age, a balance and a monthly amount']); const R = runRetire(rec, result, data); if (R.out.needs) return need(R.out.needs); const o = R.out; return { years: o.years.map((y, i) => ({ age: y.age, contributed: y.contributed, growth: y.growth, balance: y.balance, potential: o.potentialYears[i].balance })), atRetirement: o.atRetirement.balance, potential: o.potentialAtRetirement.balance, gain: o.gain, extraMonthly: o.extraMonthly, horizonAge: o.horizonAge, people: o.people, fiNumber: o.fiNumber, incomeMonthly: o.incomeMonthly }; }

export const CALC_CHARTS = [
  { id: 'calendarBalance', name: 'Cash day by day', client: 'Your cash, day by day', planet: 'spending', stage: 1, metrics: ['safeToSpend', 'lowPoint'], build: calendarBalance },
  { id: 'paycheckMap', name: 'Paycheck map', client: 'What each paycheck pays for', planet: 'spending', stage: 1, metrics: ['safeToSpend', 'takeHome'], build: paycheckMap },
  { id: 'yearStrip', name: 'The year, month by month', client: 'Your year, month by month', planet: 'spending', stage: 1, metrics: ['lowPoint'], build: yearStrip },
  { id: 'homeAnswers', name: 'How much home: three answers', client: 'Three answers on how much home', planet: 'life', stage: 3, metrics: ['shelterRate', 'fiDate'], build: homeAnswers },
  { id: 'downPaymentLadder', name: 'Down payment ladder', client: 'The down payment ladder', planet: 'life', stage: 3, metrics: ['shelterRate'], build: downPaymentLadder },
  { id: 'rentVsBuy', name: 'Rent against buy', client: 'Renting against buying, year by year', planet: 'life', stage: 3, metrics: ['shelterRate', 'netWorth'], build: rentVsBuy },
  { id: 'equityVsLoan', name: 'Home value against the loan', client: 'Home value against the loan', planet: 'life', stage: 3, metrics: ['shelterRate'], build: equityVsLoan },
  { id: 'carTco', name: 'What each car choice costs', client: 'What each car choice costs', planet: 'spending', stage: 1, metrics: ['carCostShare'], build: carTco },
  { id: 'carValueVsLoan', name: 'Car value against the loan', client: 'The car\'s value against its loan', planet: 'spending', stage: 1, metrics: ['carCostShare'], build: carValueVsLoan },
  { id: 'retireGrowth', name: 'What the investing becomes', client: 'What your investing becomes', planet: 'invest', stage: 4, metrics: ['fiNumber', 'fiDate'], build: retireGrowth },
];
