#!/usr/bin/env node
/* ==========================================================================
   tools/context/build.js — the context indexes, regenerated from the code.
   --------------------------------------------------------------------------
   Writes:
     docs/context/ROOMS.md            one line per room, by sidebar group
     docs/context/FIELDS.md           every shared field, by owner, who reads it
     docs/context/DECISIONS-INDEX.md  one line per decision, with line ranges
     docs/context/DOC-MAP.md          the big docs' headings with line ranges
     .claude/rules/rooms/<id>.md      one card per room, loaded when its files open
   Run:   node tools/context/build.js            (writes)
          node tools/context/build.js --check    (writes nothing; exit 1 if stale)
   ========================================================================== */
'use strict';
const fs = require('fs');
const path = require('path');
const L = require('./lib.js');
const CHECK = process.argv.indexOf('--check') >= 0;
const GEN = '<!-- Generated by tools/context/build.js — do not edit; run the tool. -->';

const R = L.rooms();
const roomList = R.list;
const fields = L.fields(roomList);
const decs = L.decisionIndex(roomList);
const byRoom = {};
roomList.forEach(r => { byRoom[r.id] = decs.filter(d => d.rooms.indexOf(r.id) >= 0); });
const groupLabel = {};
L.Registry.GROUPS.forEach(g => { groupLabel[g.id] = g.label; });

function latest(id, n, liveOnly) {
  return byRoom[id].filter(d => !liveOnly || !d.superseded).slice(-n).reverse();
}

/* ---- ROOMS.md ------------------------------------------------------------ */
function roomsMd() {
  const out = ['# Rooms', GEN, '', 'One line per room: id, title, lines, engines, owned fields, latest decisions.', 'Full context for one: `node tools/context/pack.js <id>`.', ''];
  L.Registry.GROUPS.forEach(g => {
    const inGroup = roomList.filter(r => r.group === g.id);
    if (!inGroup.length) return;
    out.push('## ' + g.label + ' (' + inGroup.length + ')', '');
    inGroup.forEach(r => {
      const d = latest(r.id, 3, false).map(x => x.id).join(', ');
      out.push('- **' + r.id + '** — ' + r.title + (r.utility ? ' (utility)' : '') + ' · ' + r.lines + ' lines'
        + (r.engines.length ? ' · engines: ' + r.engines.join(', ') : ' · no engines')
        + (r.owns.length ? ' · owns: ' + r.owns.join(', ') : '')
        + (d ? ' · ' + d : ''));
    });
    out.push('');
  });
  const orphans = L.orphanRoomFiles(roomList);
  out.push('## Files in rooms/ not in the registry (' + orphans.length + ')', '');
  orphans.forEach(f => out.push('- ' + f));
  out.push('');
  return out.join('\n');
}

/* ---- FIELDS.md ----------------------------------------------------------- */
function fieldsMd() {
  const out = ['# Shared fields, by owner', GEN, '',
    'A field is editable in its owner only (`shared/ownership.js`). "Read by" is a',
    'word-boundary match of the id (or id + Cents) in another room\'s HTML or in an',
    'engine loaded by two or fewer rooms; shared engines are left out so a field',
    'does not look used everywhere. Ids that are ordinary words are not traced.', ''];
  const owners = L.uniq(fields.map(f => f.owner)).sort();
  let unused = 0, traced = 0;
  owners.forEach(o => {
    const mine = fields.filter(f => f.owner === o);
    out.push('## ' + o + ' (' + mine.length + ')', '');
    mine.forEach(f => {
      if (f.generic) { out.push('- `' + f.id + '` — ' + f.label + ' · too generic to trace'); return; }
      traced++;
      if (!f.users.length) { unused++; out.push('- `' + f.id + '` — ' + f.label + ' · **no other room mentions it**'); }
      else out.push('- `' + f.id + '` — ' + f.label + ' · read by ' + f.users.join(', '));
    });
    out.push('');
  });
  out.splice(7, 0, 'Fields: ' + fields.length + '. Traced: ' + traced + '. No other room mentions it: **' + unused + '**.', '');
  return out.join('\n');
}

/* ---- DECISIONS-INDEX.md -------------------------------------------------- */
function decisionsIndexMd() {
  const out = ['# Decisions index', GEN, '',
    'One line per entry in DECISIONS.md: id, title, `[start-end]` lines, `{rooms}` it',
    'touches. `~` marks an entry a later one supersedes. Read one with',
    '`node tools/context/pack.js D-123` or `sed -n START,ENDp DECISIONS.md`.', ''];
  const sparks = decs.filter(d => !d.dnd), dnd = decs.filter(d => d.dnd);
  [['SPARKS (D-)', sparks], ['Dungeons & Dividends (DD-)', dnd]].forEach(pair => {
    out.push('## ' + pair[0] + ' (' + pair[1].length + ')', '');
    pair[1].forEach(d => {
      const rooms = d.rooms.length > 6 ? 'many rooms' : d.rooms.join(', ');
      out.push('- ' + (d.superseded ? '~' : '') + d.id + ' — ' + d.title + ' [' + d.start + '-' + d.end + ']' + (rooms ? ' {' + rooms + '}' : ''));
    });
    out.push('');
  });
  return out.join('\n');
}

/* ---- DOC-MAP.md ---------------------------------------------------------- */
function docMapMd() {
  const out = ['# Document map', GEN, '', 'Level 1 and 2 headings of the big documents with their line ranges, so a', 'section can be read with `sed -n START,ENDp FILE` instead of the whole file.', ''];
  ['SPEC.md', 'ROADMAP.md', 'MONEY-MAP.md', 'DESIGN-AUDIT.md', 'LATER.md', 'README.md'].forEach(f => {
    const d = L.docHeadings(f);
    out.push('## ' + f + ' (' + d.total + ' lines)', '');
    d.heads.forEach(h => out.push((h.level === 2 ? '  - ' : '- ') + h.title + ' [' + h.start + '-' + h.end + ']'));
    out.push('');
  });
  return out.join('\n');
}

/* ---- Room cards ---------------------------------------------------------- */
function fieldOwner(id) { return L.Ownership.FIELDS[id].owner; }
function cardMd(r) {
  const paths = [r.href].concat(r.rareEngines.map(e => 'engines/' + e + '.js'));
  const reads = fields.filter(f => f.owner !== r.id && !f.generic && f.users.indexOf(r.id) >= 0).map(f => f.id + ' (' + f.owner + ')');
  const cap = (arr, n) => arr.length > n ? arr.slice(0, n).concat(['+' + (arr.length - n) + ' more']) : arr;
  const out = ['---', 'paths:'].concat(paths.map(p => '  - "' + p + '"')).concat(['---',
    '# ' + r.title + ' (`' + r.id + '`)',
    'File: ' + r.href + ' · ' + r.lines + ' lines' + (r.utility ? ' · utility room' : ''),
    'Engines: ' + (r.engines.length ? r.engines.join(', ') : 'none'),
    'Reference data: ' + (r.data.length ? cap(r.data, 6).join(', ') : 'none'),
    'Owns: ' + (r.owns.length ? r.owns.join(', ') : 'nothing'),
    'Reads from other owners: ' + (reads.length ? cap(reads, 8).join(', ') : 'nothing traced'),
    'Latest decisions:']);
  const live = latest(r.id, 5, true);
  if (!live.length) out.push('  (none linked)');
  live.forEach(d => out.push('  - ' + d.id + ' — ' + d.title));
  out.push('Full context: node tools/context/pack.js ' + r.id, '');
  return out.join('\n');
}

/* ---- Write or check ----------------------------------------------------- */
const outputs = {
  'docs/context/ROOMS.md': roomsMd(),
  'docs/context/FIELDS.md': fieldsMd(),
  'docs/context/DECISIONS-INDEX.md': decisionsIndexMd(),
  'docs/context/DOC-MAP.md': docMapMd()
};
roomList.forEach(r => { outputs['.claude/rules/rooms/' + r.id + '.md'] = cardMd(r); });

/* A card for a room that left the registry is stale too. */
const cardDir = path.join(L.ROOT, '.claude/rules/rooms');
const stray = fs.existsSync(cardDir) ? fs.readdirSync(cardDir).filter(f => /\.md$/.test(f) && !outputs['.claude/rules/rooms/' + f]) : [];

const stale = Object.keys(outputs).filter(rel => L.read(rel) !== outputs[rel]);
if (CHECK) {
  if (!stale.length && !stray.length) { console.log('context files are current (' + Object.keys(outputs).length + ' files)'); process.exit(0); }
  stale.forEach(f => console.log('stale: ' + f));
  stray.forEach(f => console.log('stray card: .claude/rules/rooms/' + f));
  console.log('run: node tools/context/build.js');
  process.exit(1);
}
Object.keys(outputs).forEach(rel => {
  const abs = path.join(L.ROOT, rel);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, outputs[rel]);
});
stray.forEach(f => fs.unlinkSync(path.join(cardDir, f)));
console.log('wrote ' + Object.keys(outputs).length + ' files (' + stale.length + ' changed' + (stray.length ? ', ' + stray.length + ' stray cards removed' : '') + ')');
